packages:
  - "."
  - "sdks/*"
allowBuilds:
  "@quobix/vacuum": true
  core-js: false
  esbuild: true
  protobufjs: true
  unrs-resolver: true
catalog:
  "@vitest/coverage-v8": 5.0.3
  vite: npm:@voidzero-dev/vite-plus-core@1.1.0
  vite-plus: 1.1.0
  vitest: 5.0.3
overrides:
  "axios": "^1.20.0"
  "form-data": "^4.0.6"
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
