type: object
required:
  - name
  - description
  - price
  - currency
properties:
  name:
    description: Name of product
    type: string
  description:
    description: The description of the product
    type: string
  price:
    description: >
      Price should be in the subunit of the supported currency (e.g. kobo for NGN, pesewas for GHS, cents for ZAR/USD/KES).
      For XOF, the price is the same as the base units (not multiplied by 100).
    type: integer
  currency:
    description: |
      Currency in which price is set. Allowed values are: NGN, GHS, ZAR, USD or XOF
    type: string
  unlimited:
    description: |
      Set to true if the product has unlimited stock. Leave as false if the
      product has limited stock
    type: boolean
  quantity:
    description: Number of products in stock. Use if limited is true
    type: integer
  split_code:
    description: The split code if sharing the transaction with partners
    type: string
  metadata:
    description: Stringified JSON object of custom data
    type: string
example:
  name: Cups
  description: Environment friendly paper cups
  price: 10000
  currency: NGN
