/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
)

// checks if the SubscriptionCreateResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionCreateResponseData{}

// SubscriptionCreateResponseData struct for SubscriptionCreateResponseData
type SubscriptionCreateResponseData struct {
	Customer int32 `json:"customer"`
	Plan int32 `json:"plan"`
	Integration int32 `json:"integration"`
	Domain string `json:"domain"`
	Start int32 `json:"start"`
	Status string `json:"status"`
	Quantity int32 `json:"quantity"`
	Amount int32 `json:"amount"`
	Authorization int32 `json:"authorization"`
	InvoiceLimit int32 `json:"invoice_limit"`
	SplitCode interface{} `json:"split_code"`
	SubscriptionCode string `json:"subscription_code"`
	EmailToken string `json:"email_token"`
	Id int32 `json:"id"`
	CancelledAt interface{} `json:"cancelledAt"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	CronExpression string `json:"cron_expression"`
	NextPaymentDate string `json:"next_payment_date"`
	EasyCronId NullableString `json:"easy_cron_id"`
	OpenInvoice NullableString `json:"open_invoice"`
	Metadata map[string]interface{} `json:"metadata"`
}

// NewSubscriptionCreateResponseData instantiates a new SubscriptionCreateResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionCreateResponseData(customer int32, plan int32, integration int32, domain string, start int32, status string, quantity int32, amount int32, authorization int32, invoiceLimit int32, splitCode interface{}, subscriptionCode string, emailToken string, id int32, cancelledAt interface{}, createdAt string, updatedAt string, cronExpression string, nextPaymentDate string, easyCronId NullableString, openInvoice NullableString, metadata map[string]interface{}) *SubscriptionCreateResponseData {
	this := SubscriptionCreateResponseData{}
	this.Customer = customer
	this.Plan = plan
	this.Integration = integration
	this.Domain = domain
	this.Start = start
	this.Status = status
	this.Quantity = quantity
	this.Amount = amount
	this.Authorization = authorization
	this.InvoiceLimit = invoiceLimit
	this.SplitCode = splitCode
	this.SubscriptionCode = subscriptionCode
	this.EmailToken = emailToken
	this.Id = id
	this.CancelledAt = cancelledAt
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.CronExpression = cronExpression
	this.NextPaymentDate = nextPaymentDate
	this.EasyCronId = easyCronId
	this.OpenInvoice = openInvoice
	this.Metadata = metadata
	return &this
}

// NewSubscriptionCreateResponseDataWithDefaults instantiates a new SubscriptionCreateResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionCreateResponseDataWithDefaults() *SubscriptionCreateResponseData {
	this := SubscriptionCreateResponseData{}
	return &this
}

// GetCustomer returns the Customer field value
func (o *SubscriptionCreateResponseData) GetCustomer() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Customer
}

// GetCustomerOk returns a tuple with the Customer field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateResponseData) GetCustomerOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Customer, true
}

// SetCustomer sets field value
func (o *SubscriptionCreateResponseData) SetCustomer(v int32) {
	o.Customer = v
}

// GetPlan returns the Plan field value
func (o *SubscriptionCreateResponseData) GetPlan() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Plan
}

// GetPlanOk returns a tuple with the Plan field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateResponseData) GetPlanOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plan, true
}

// SetPlan sets field value
func (o *SubscriptionCreateResponseData) SetPlan(v int32) {
	o.Plan = v
}

// GetIntegration returns the Integration field value
func (o *SubscriptionCreateResponseData) GetIntegration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Integration
}

// GetIntegrationOk returns a tuple with the Integration field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateResponseData) GetIntegrationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Integration, true
}

// SetIntegration sets field value
func (o *SubscriptionCreateResponseData) SetIntegration(v int32) {
	o.Integration = v
}

// GetDomain returns the Domain field value
func (o *SubscriptionCreateResponseData) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateResponseData) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *SubscriptionCreateResponseData) SetDomain(v string) {
	o.Domain = v
}

// GetStart returns the Start field value
func (o *SubscriptionCreateResponseData) GetStart() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateResponseData) GetStartOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *SubscriptionCreateResponseData) SetStart(v int32) {
	o.Start = v
}

// GetStatus returns the Status field value
func (o *SubscriptionCreateResponseData) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateResponseData) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SubscriptionCreateResponseData) SetStatus(v string) {
	o.Status = v
}

// GetQuantity returns the Quantity field value
func (o *SubscriptionCreateResponseData) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateResponseData) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *SubscriptionCreateResponseData) SetQuantity(v int32) {
	o.Quantity = v
}

// GetAmount returns the Amount field value
func (o *SubscriptionCreateResponseData) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateResponseData) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *SubscriptionCreateResponseData) SetAmount(v int32) {
	o.Amount = v
}

// GetAuthorization returns the Authorization field value
func (o *SubscriptionCreateResponseData) GetAuthorization() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Authorization
}

// GetAuthorizationOk returns a tuple with the Authorization field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateResponseData) GetAuthorizationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Authorization, true
}

// SetAuthorization sets field value
func (o *SubscriptionCreateResponseData) SetAuthorization(v int32) {
	o.Authorization = v
}

// GetInvoiceLimit returns the InvoiceLimit field value
func (o *SubscriptionCreateResponseData) GetInvoiceLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InvoiceLimit
}

// GetInvoiceLimitOk returns a tuple with the InvoiceLimit field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateResponseData) GetInvoiceLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvoiceLimit, true
}

// SetInvoiceLimit sets field value
func (o *SubscriptionCreateResponseData) SetInvoiceLimit(v int32) {
	o.InvoiceLimit = v
}

// GetSplitCode returns the SplitCode field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *SubscriptionCreateResponseData) GetSplitCode() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.SplitCode
}

// GetSplitCodeOk returns a tuple with the SplitCode field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubscriptionCreateResponseData) GetSplitCodeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SplitCode) {
		return nil, false
	}
	return &o.SplitCode, true
}

// SetSplitCode sets field value
func (o *SubscriptionCreateResponseData) SetSplitCode(v interface{}) {
	o.SplitCode = v
}

// GetSubscriptionCode returns the SubscriptionCode field value
func (o *SubscriptionCreateResponseData) GetSubscriptionCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubscriptionCode
}

// GetSubscriptionCodeOk returns a tuple with the SubscriptionCode field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateResponseData) GetSubscriptionCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubscriptionCode, true
}

// SetSubscriptionCode sets field value
func (o *SubscriptionCreateResponseData) SetSubscriptionCode(v string) {
	o.SubscriptionCode = v
}

// GetEmailToken returns the EmailToken field value
func (o *SubscriptionCreateResponseData) GetEmailToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmailToken
}

// GetEmailTokenOk returns a tuple with the EmailToken field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateResponseData) GetEmailTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmailToken, true
}

// SetEmailToken sets field value
func (o *SubscriptionCreateResponseData) SetEmailToken(v string) {
	o.EmailToken = v
}

// GetId returns the Id field value
func (o *SubscriptionCreateResponseData) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateResponseData) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SubscriptionCreateResponseData) SetId(v int32) {
	o.Id = v
}

// GetCancelledAt returns the CancelledAt field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *SubscriptionCreateResponseData) GetCancelledAt() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.CancelledAt
}

// GetCancelledAtOk returns a tuple with the CancelledAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubscriptionCreateResponseData) GetCancelledAtOk() (*interface{}, bool) {
	if o == nil || IsNil(o.CancelledAt) {
		return nil, false
	}
	return &o.CancelledAt, true
}

// SetCancelledAt sets field value
func (o *SubscriptionCreateResponseData) SetCancelledAt(v interface{}) {
	o.CancelledAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *SubscriptionCreateResponseData) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateResponseData) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SubscriptionCreateResponseData) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *SubscriptionCreateResponseData) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateResponseData) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *SubscriptionCreateResponseData) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetCronExpression returns the CronExpression field value
func (o *SubscriptionCreateResponseData) GetCronExpression() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CronExpression
}

// GetCronExpressionOk returns a tuple with the CronExpression field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateResponseData) GetCronExpressionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CronExpression, true
}

// SetCronExpression sets field value
func (o *SubscriptionCreateResponseData) SetCronExpression(v string) {
	o.CronExpression = v
}

// GetNextPaymentDate returns the NextPaymentDate field value
func (o *SubscriptionCreateResponseData) GetNextPaymentDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextPaymentDate
}

// GetNextPaymentDateOk returns a tuple with the NextPaymentDate field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateResponseData) GetNextPaymentDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextPaymentDate, true
}

// SetNextPaymentDate sets field value
func (o *SubscriptionCreateResponseData) SetNextPaymentDate(v string) {
	o.NextPaymentDate = v
}

// GetEasyCronId returns the EasyCronId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SubscriptionCreateResponseData) GetEasyCronId() string {
	if o == nil || o.EasyCronId.Get() == nil {
		var ret string
		return ret
	}

	return *o.EasyCronId.Get()
}

// GetEasyCronIdOk returns a tuple with the EasyCronId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubscriptionCreateResponseData) GetEasyCronIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EasyCronId.Get(), o.EasyCronId.IsSet()
}

// SetEasyCronId sets field value
func (o *SubscriptionCreateResponseData) SetEasyCronId(v string) {
	o.EasyCronId.Set(&v)
}

// GetOpenInvoice returns the OpenInvoice field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SubscriptionCreateResponseData) GetOpenInvoice() string {
	if o == nil || o.OpenInvoice.Get() == nil {
		var ret string
		return ret
	}

	return *o.OpenInvoice.Get()
}

// GetOpenInvoiceOk returns a tuple with the OpenInvoice field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubscriptionCreateResponseData) GetOpenInvoiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OpenInvoice.Get(), o.OpenInvoice.IsSet()
}

// SetOpenInvoice sets field value
func (o *SubscriptionCreateResponseData) SetOpenInvoice(v string) {
	o.OpenInvoice.Set(&v)
}

// GetMetadata returns the Metadata field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *SubscriptionCreateResponseData) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubscriptionCreateResponseData) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// SetMetadata sets field value
func (o *SubscriptionCreateResponseData) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o SubscriptionCreateResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionCreateResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["customer"] = o.Customer
	toSerialize["plan"] = o.Plan
	toSerialize["integration"] = o.Integration
	toSerialize["domain"] = o.Domain
	toSerialize["start"] = o.Start
	toSerialize["status"] = o.Status
	toSerialize["quantity"] = o.Quantity
	toSerialize["amount"] = o.Amount
	toSerialize["authorization"] = o.Authorization
	toSerialize["invoice_limit"] = o.InvoiceLimit
	if o.SplitCode != nil {
		toSerialize["split_code"] = o.SplitCode
	}
	toSerialize["subscription_code"] = o.SubscriptionCode
	toSerialize["email_token"] = o.EmailToken
	toSerialize["id"] = o.Id
	if o.CancelledAt != nil {
		toSerialize["cancelledAt"] = o.CancelledAt
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["cron_expression"] = o.CronExpression
	toSerialize["next_payment_date"] = o.NextPaymentDate
	toSerialize["easy_cron_id"] = o.EasyCronId.Get()
	toSerialize["open_invoice"] = o.OpenInvoice.Get()
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableSubscriptionCreateResponseData struct {
	value *SubscriptionCreateResponseData
	isSet bool
}

func (v NullableSubscriptionCreateResponseData) Get() *SubscriptionCreateResponseData {
	return v.value
}

func (v *NullableSubscriptionCreateResponseData) Set(val *SubscriptionCreateResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionCreateResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionCreateResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionCreateResponseData(val *SubscriptionCreateResponseData) *NullableSubscriptionCreateResponseData {
	return &NullableSubscriptionCreateResponseData{value: val, isSet: true}
}

func (v NullableSubscriptionCreateResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionCreateResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


