/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductFetchResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductFetchResponseData{}

// ProductFetchResponseData struct for ProductFetchResponseData
type ProductFetchResponseData struct {
	DigitalAssets []interface{} `json:"digital_assets"`
	Integration int32 `json:"integration"`
	Name string `json:"name"`
	Description string `json:"description"`
	ProductCode string `json:"product_code"`
	Price int32 `json:"price"`
	Currency string `json:"currency"`
	Quantity int32 `json:"quantity"`
	QuantitySold interface{} `json:"quantity_sold"`
	Type string `json:"type"`
	Files []interface{} `json:"files"`
	FilePath interface{} `json:"file_path"`
	IsShippable bool `json:"is_shippable"`
	ShippingFields ProductListsResponseArrayShippingFields `json:"shipping_fields"`
	Unlimited bool `json:"unlimited"`
	Domain string `json:"domain"`
	Active bool `json:"active"`
	Features interface{} `json:"features"`
	InStock bool `json:"in_stock"`
	Metadata ProductListsResponseArrayMetadata `json:"metadata"`
	Slug string `json:"slug"`
	SuccessMessage interface{} `json:"success_message"`
	RedirectUrl interface{} `json:"redirect_url"`
	SplitCode interface{} `json:"split_code"`
	NotificationEmails interface{} `json:"notification_emails"`
	MinimumOrderable int32 `json:"minimum_orderable"`
	MaximumOrderable interface{} `json:"maximum_orderable"`
	LowStockAlert bool `json:"low_stock_alert"`
	StockThreshold interface{} `json:"stock_threshold"`
	ExpiresIn interface{} `json:"expires_in"`
	Id int32 `json:"id"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type _ProductFetchResponseData ProductFetchResponseData

// NewProductFetchResponseData instantiates a new ProductFetchResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductFetchResponseData(digitalAssets []interface{}, integration int32, name string, description string, productCode string, price int32, currency string, quantity int32, quantitySold interface{}, type_ string, files []interface{}, filePath interface{}, isShippable bool, shippingFields ProductListsResponseArrayShippingFields, unlimited bool, domain string, active bool, features interface{}, inStock bool, metadata ProductListsResponseArrayMetadata, slug string, successMessage interface{}, redirectUrl interface{}, splitCode interface{}, notificationEmails interface{}, minimumOrderable int32, maximumOrderable interface{}, lowStockAlert bool, stockThreshold interface{}, expiresIn interface{}, id int32, createdAt string, updatedAt string) *ProductFetchResponseData {
	this := ProductFetchResponseData{}
	this.DigitalAssets = digitalAssets
	this.Integration = integration
	this.Name = name
	this.Description = description
	this.ProductCode = productCode
	this.Price = price
	this.Currency = currency
	this.Quantity = quantity
	this.QuantitySold = quantitySold
	this.Type = type_
	this.Files = files
	this.FilePath = filePath
	this.IsShippable = isShippable
	this.ShippingFields = shippingFields
	this.Unlimited = unlimited
	this.Domain = domain
	this.Active = active
	this.Features = features
	this.InStock = inStock
	this.Metadata = metadata
	this.Slug = slug
	this.SuccessMessage = successMessage
	this.RedirectUrl = redirectUrl
	this.SplitCode = splitCode
	this.NotificationEmails = notificationEmails
	this.MinimumOrderable = minimumOrderable
	this.MaximumOrderable = maximumOrderable
	this.LowStockAlert = lowStockAlert
	this.StockThreshold = stockThreshold
	this.ExpiresIn = expiresIn
	this.Id = id
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewProductFetchResponseDataWithDefaults instantiates a new ProductFetchResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductFetchResponseDataWithDefaults() *ProductFetchResponseData {
	this := ProductFetchResponseData{}
	return &this
}

// GetDigitalAssets returns the DigitalAssets field value
func (o *ProductFetchResponseData) GetDigitalAssets() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.DigitalAssets
}

// GetDigitalAssetsOk returns a tuple with the DigitalAssets field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetDigitalAssetsOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.DigitalAssets, true
}

// SetDigitalAssets sets field value
func (o *ProductFetchResponseData) SetDigitalAssets(v []interface{}) {
	o.DigitalAssets = v
}

// GetIntegration returns the Integration field value
func (o *ProductFetchResponseData) GetIntegration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Integration
}

// GetIntegrationOk returns a tuple with the Integration field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetIntegrationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Integration, true
}

// SetIntegration sets field value
func (o *ProductFetchResponseData) SetIntegration(v int32) {
	o.Integration = v
}

// GetName returns the Name field value
func (o *ProductFetchResponseData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProductFetchResponseData) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *ProductFetchResponseData) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ProductFetchResponseData) SetDescription(v string) {
	o.Description = v
}

// GetProductCode returns the ProductCode field value
func (o *ProductFetchResponseData) GetProductCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductCode
}

// GetProductCodeOk returns a tuple with the ProductCode field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetProductCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductCode, true
}

// SetProductCode sets field value
func (o *ProductFetchResponseData) SetProductCode(v string) {
	o.ProductCode = v
}

// GetPrice returns the Price field value
func (o *ProductFetchResponseData) GetPrice() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetPriceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *ProductFetchResponseData) SetPrice(v int32) {
	o.Price = v
}

// GetCurrency returns the Currency field value
func (o *ProductFetchResponseData) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *ProductFetchResponseData) SetCurrency(v string) {
	o.Currency = v
}

// GetQuantity returns the Quantity field value
func (o *ProductFetchResponseData) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *ProductFetchResponseData) SetQuantity(v int32) {
	o.Quantity = v
}

// GetQuantitySold returns the QuantitySold field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ProductFetchResponseData) GetQuantitySold() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.QuantitySold
}

// GetQuantitySoldOk returns a tuple with the QuantitySold field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductFetchResponseData) GetQuantitySoldOk() (*interface{}, bool) {
	if o == nil || IsNil(o.QuantitySold) {
		return nil, false
	}
	return &o.QuantitySold, true
}

// SetQuantitySold sets field value
func (o *ProductFetchResponseData) SetQuantitySold(v interface{}) {
	o.QuantitySold = v
}

// GetType returns the Type field value
func (o *ProductFetchResponseData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ProductFetchResponseData) SetType(v string) {
	o.Type = v
}

// GetFiles returns the Files field value
func (o *ProductFetchResponseData) GetFiles() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Files
}

// GetFilesOk returns a tuple with the Files field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetFilesOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Files, true
}

// SetFiles sets field value
func (o *ProductFetchResponseData) SetFiles(v []interface{}) {
	o.Files = v
}

// GetFilePath returns the FilePath field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ProductFetchResponseData) GetFilePath() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.FilePath
}

// GetFilePathOk returns a tuple with the FilePath field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductFetchResponseData) GetFilePathOk() (*interface{}, bool) {
	if o == nil || IsNil(o.FilePath) {
		return nil, false
	}
	return &o.FilePath, true
}

// SetFilePath sets field value
func (o *ProductFetchResponseData) SetFilePath(v interface{}) {
	o.FilePath = v
}

// GetIsShippable returns the IsShippable field value
func (o *ProductFetchResponseData) GetIsShippable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsShippable
}

// GetIsShippableOk returns a tuple with the IsShippable field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetIsShippableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsShippable, true
}

// SetIsShippable sets field value
func (o *ProductFetchResponseData) SetIsShippable(v bool) {
	o.IsShippable = v
}

// GetShippingFields returns the ShippingFields field value
func (o *ProductFetchResponseData) GetShippingFields() ProductListsResponseArrayShippingFields {
	if o == nil {
		var ret ProductListsResponseArrayShippingFields
		return ret
	}

	return o.ShippingFields
}

// GetShippingFieldsOk returns a tuple with the ShippingFields field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetShippingFieldsOk() (*ProductListsResponseArrayShippingFields, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShippingFields, true
}

// SetShippingFields sets field value
func (o *ProductFetchResponseData) SetShippingFields(v ProductListsResponseArrayShippingFields) {
	o.ShippingFields = v
}

// GetUnlimited returns the Unlimited field value
func (o *ProductFetchResponseData) GetUnlimited() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Unlimited
}

// GetUnlimitedOk returns a tuple with the Unlimited field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetUnlimitedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unlimited, true
}

// SetUnlimited sets field value
func (o *ProductFetchResponseData) SetUnlimited(v bool) {
	o.Unlimited = v
}

// GetDomain returns the Domain field value
func (o *ProductFetchResponseData) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *ProductFetchResponseData) SetDomain(v string) {
	o.Domain = v
}

// GetActive returns the Active field value
func (o *ProductFetchResponseData) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *ProductFetchResponseData) SetActive(v bool) {
	o.Active = v
}

// GetFeatures returns the Features field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ProductFetchResponseData) GetFeatures() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductFetchResponseData) GetFeaturesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return &o.Features, true
}

// SetFeatures sets field value
func (o *ProductFetchResponseData) SetFeatures(v interface{}) {
	o.Features = v
}

// GetInStock returns the InStock field value
func (o *ProductFetchResponseData) GetInStock() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.InStock
}

// GetInStockOk returns a tuple with the InStock field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetInStockOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InStock, true
}

// SetInStock sets field value
func (o *ProductFetchResponseData) SetInStock(v bool) {
	o.InStock = v
}

// GetMetadata returns the Metadata field value
func (o *ProductFetchResponseData) GetMetadata() ProductListsResponseArrayMetadata {
	if o == nil {
		var ret ProductListsResponseArrayMetadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetMetadataOk() (*ProductListsResponseArrayMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *ProductFetchResponseData) SetMetadata(v ProductListsResponseArrayMetadata) {
	o.Metadata = v
}

// GetSlug returns the Slug field value
func (o *ProductFetchResponseData) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *ProductFetchResponseData) SetSlug(v string) {
	o.Slug = v
}

// GetSuccessMessage returns the SuccessMessage field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ProductFetchResponseData) GetSuccessMessage() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.SuccessMessage
}

// GetSuccessMessageOk returns a tuple with the SuccessMessage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductFetchResponseData) GetSuccessMessageOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SuccessMessage) {
		return nil, false
	}
	return &o.SuccessMessage, true
}

// SetSuccessMessage sets field value
func (o *ProductFetchResponseData) SetSuccessMessage(v interface{}) {
	o.SuccessMessage = v
}

// GetRedirectUrl returns the RedirectUrl field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ProductFetchResponseData) GetRedirectUrl() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.RedirectUrl
}

// GetRedirectUrlOk returns a tuple with the RedirectUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductFetchResponseData) GetRedirectUrlOk() (*interface{}, bool) {
	if o == nil || IsNil(o.RedirectUrl) {
		return nil, false
	}
	return &o.RedirectUrl, true
}

// SetRedirectUrl sets field value
func (o *ProductFetchResponseData) SetRedirectUrl(v interface{}) {
	o.RedirectUrl = v
}

// GetSplitCode returns the SplitCode field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ProductFetchResponseData) GetSplitCode() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.SplitCode
}

// GetSplitCodeOk returns a tuple with the SplitCode field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductFetchResponseData) GetSplitCodeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SplitCode) {
		return nil, false
	}
	return &o.SplitCode, true
}

// SetSplitCode sets field value
func (o *ProductFetchResponseData) SetSplitCode(v interface{}) {
	o.SplitCode = v
}

// GetNotificationEmails returns the NotificationEmails field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ProductFetchResponseData) GetNotificationEmails() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.NotificationEmails
}

// GetNotificationEmailsOk returns a tuple with the NotificationEmails field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductFetchResponseData) GetNotificationEmailsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.NotificationEmails) {
		return nil, false
	}
	return &o.NotificationEmails, true
}

// SetNotificationEmails sets field value
func (o *ProductFetchResponseData) SetNotificationEmails(v interface{}) {
	o.NotificationEmails = v
}

// GetMinimumOrderable returns the MinimumOrderable field value
func (o *ProductFetchResponseData) GetMinimumOrderable() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MinimumOrderable
}

// GetMinimumOrderableOk returns a tuple with the MinimumOrderable field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetMinimumOrderableOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinimumOrderable, true
}

// SetMinimumOrderable sets field value
func (o *ProductFetchResponseData) SetMinimumOrderable(v int32) {
	o.MinimumOrderable = v
}

// GetMaximumOrderable returns the MaximumOrderable field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ProductFetchResponseData) GetMaximumOrderable() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.MaximumOrderable
}

// GetMaximumOrderableOk returns a tuple with the MaximumOrderable field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductFetchResponseData) GetMaximumOrderableOk() (*interface{}, bool) {
	if o == nil || IsNil(o.MaximumOrderable) {
		return nil, false
	}
	return &o.MaximumOrderable, true
}

// SetMaximumOrderable sets field value
func (o *ProductFetchResponseData) SetMaximumOrderable(v interface{}) {
	o.MaximumOrderable = v
}

// GetLowStockAlert returns the LowStockAlert field value
func (o *ProductFetchResponseData) GetLowStockAlert() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.LowStockAlert
}

// GetLowStockAlertOk returns a tuple with the LowStockAlert field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetLowStockAlertOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LowStockAlert, true
}

// SetLowStockAlert sets field value
func (o *ProductFetchResponseData) SetLowStockAlert(v bool) {
	o.LowStockAlert = v
}

// GetStockThreshold returns the StockThreshold field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ProductFetchResponseData) GetStockThreshold() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.StockThreshold
}

// GetStockThresholdOk returns a tuple with the StockThreshold field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductFetchResponseData) GetStockThresholdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.StockThreshold) {
		return nil, false
	}
	return &o.StockThreshold, true
}

// SetStockThreshold sets field value
func (o *ProductFetchResponseData) SetStockThreshold(v interface{}) {
	o.StockThreshold = v
}

// GetExpiresIn returns the ExpiresIn field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ProductFetchResponseData) GetExpiresIn() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductFetchResponseData) GetExpiresInOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ExpiresIn) {
		return nil, false
	}
	return &o.ExpiresIn, true
}

// SetExpiresIn sets field value
func (o *ProductFetchResponseData) SetExpiresIn(v interface{}) {
	o.ExpiresIn = v
}

// GetId returns the Id field value
func (o *ProductFetchResponseData) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProductFetchResponseData) SetId(v int32) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ProductFetchResponseData) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ProductFetchResponseData) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ProductFetchResponseData) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ProductFetchResponseData) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ProductFetchResponseData) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o ProductFetchResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductFetchResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["digital_assets"] = o.DigitalAssets
	toSerialize["integration"] = o.Integration
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["product_code"] = o.ProductCode
	toSerialize["price"] = o.Price
	toSerialize["currency"] = o.Currency
	toSerialize["quantity"] = o.Quantity
	if o.QuantitySold != nil {
		toSerialize["quantity_sold"] = o.QuantitySold
	}
	toSerialize["type"] = o.Type
	toSerialize["files"] = o.Files
	if o.FilePath != nil {
		toSerialize["file_path"] = o.FilePath
	}
	toSerialize["is_shippable"] = o.IsShippable
	toSerialize["shipping_fields"] = o.ShippingFields
	toSerialize["unlimited"] = o.Unlimited
	toSerialize["domain"] = o.Domain
	toSerialize["active"] = o.Active
	if o.Features != nil {
		toSerialize["features"] = o.Features
	}
	toSerialize["in_stock"] = o.InStock
	toSerialize["metadata"] = o.Metadata
	toSerialize["slug"] = o.Slug
	if o.SuccessMessage != nil {
		toSerialize["success_message"] = o.SuccessMessage
	}
	if o.RedirectUrl != nil {
		toSerialize["redirect_url"] = o.RedirectUrl
	}
	if o.SplitCode != nil {
		toSerialize["split_code"] = o.SplitCode
	}
	if o.NotificationEmails != nil {
		toSerialize["notification_emails"] = o.NotificationEmails
	}
	toSerialize["minimum_orderable"] = o.MinimumOrderable
	if o.MaximumOrderable != nil {
		toSerialize["maximum_orderable"] = o.MaximumOrderable
	}
	toSerialize["low_stock_alert"] = o.LowStockAlert
	if o.StockThreshold != nil {
		toSerialize["stock_threshold"] = o.StockThreshold
	}
	if o.ExpiresIn != nil {
		toSerialize["expires_in"] = o.ExpiresIn
	}
	toSerialize["id"] = o.Id
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *ProductFetchResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"digital_assets",
		"integration",
		"name",
		"description",
		"product_code",
		"price",
		"currency",
		"quantity",
		"quantity_sold",
		"type",
		"files",
		"file_path",
		"is_shippable",
		"shipping_fields",
		"unlimited",
		"domain",
		"active",
		"features",
		"in_stock",
		"metadata",
		"slug",
		"success_message",
		"redirect_url",
		"split_code",
		"notification_emails",
		"minimum_orderable",
		"maximum_orderable",
		"low_stock_alert",
		"stock_threshold",
		"expires_in",
		"id",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductFetchResponseData := _ProductFetchResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductFetchResponseData)

	if err != nil {
		return err
	}

	*o = ProductFetchResponseData(varProductFetchResponseData)

	return err
}

type NullableProductFetchResponseData struct {
	value *ProductFetchResponseData
	isSet bool
}

func (v NullableProductFetchResponseData) Get() *ProductFetchResponseData {
	return v.value
}

func (v *NullableProductFetchResponseData) Set(val *ProductFetchResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableProductFetchResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableProductFetchResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductFetchResponseData(val *ProductFetchResponseData) *NullableProductFetchResponseData {
	return &NullableProductFetchResponseData{value: val, isSet: true}
}

func (v NullableProductFetchResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductFetchResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


