/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlanFetchResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlanFetchResponseData{}

// PlanFetchResponseData struct for PlanFetchResponseData
type PlanFetchResponseData struct {
	Subscriptions []interface{} `json:"subscriptions"`
	Pages []interface{} `json:"pages"`
	Domain string `json:"domain"`
	Name string `json:"name"`
	PlanCode string `json:"plan_code"`
	Description interface{} `json:"description"`
	Amount int32 `json:"amount"`
	Interval string `json:"interval"`
	InvoiceLimit int32 `json:"invoice_limit"`
	SendInvoices bool `json:"send_invoices"`
	SendSms bool `json:"send_sms"`
	HostedPage bool `json:"hosted_page"`
	HostedPageUrl interface{} `json:"hosted_page_url"`
	HostedPageSummary interface{} `json:"hosted_page_summary"`
	Currency string `json:"currency"`
	Migrate bool `json:"migrate"`
	IsDeleted bool `json:"is_deleted"`
	IsArchived bool `json:"is_archived"`
	Id int32 `json:"id"`
	Integration int32 `json:"integration"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	PagesCount int32 `json:"pages_count"`
	SubscribersCount int32 `json:"subscribers_count"`
	SubscriptionsCount int32 `json:"subscriptions_count"`
	ActiveSubscriptionsCount NullableInt32 `json:"active_subscriptions_count"`
	TotalRevenue int32 `json:"total_revenue"`
	Subscribers []interface{} `json:"subscribers"`
}

type _PlanFetchResponseData PlanFetchResponseData

// NewPlanFetchResponseData instantiates a new PlanFetchResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanFetchResponseData(subscriptions []interface{}, pages []interface{}, domain string, name string, planCode string, description interface{}, amount int32, interval string, invoiceLimit int32, sendInvoices bool, sendSms bool, hostedPage bool, hostedPageUrl interface{}, hostedPageSummary interface{}, currency string, migrate bool, isDeleted bool, isArchived bool, id int32, integration int32, createdAt string, updatedAt string, pagesCount int32, subscribersCount int32, subscriptionsCount int32, activeSubscriptionsCount NullableInt32, totalRevenue int32, subscribers []interface{}) *PlanFetchResponseData {
	this := PlanFetchResponseData{}
	this.Subscriptions = subscriptions
	this.Pages = pages
	this.Domain = domain
	this.Name = name
	this.PlanCode = planCode
	this.Description = description
	this.Amount = amount
	this.Interval = interval
	this.InvoiceLimit = invoiceLimit
	this.SendInvoices = sendInvoices
	this.SendSms = sendSms
	this.HostedPage = hostedPage
	this.HostedPageUrl = hostedPageUrl
	this.HostedPageSummary = hostedPageSummary
	this.Currency = currency
	this.Migrate = migrate
	this.IsDeleted = isDeleted
	this.IsArchived = isArchived
	this.Id = id
	this.Integration = integration
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.PagesCount = pagesCount
	this.SubscribersCount = subscribersCount
	this.SubscriptionsCount = subscriptionsCount
	this.ActiveSubscriptionsCount = activeSubscriptionsCount
	this.TotalRevenue = totalRevenue
	this.Subscribers = subscribers
	return &this
}

// NewPlanFetchResponseDataWithDefaults instantiates a new PlanFetchResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanFetchResponseDataWithDefaults() *PlanFetchResponseData {
	this := PlanFetchResponseData{}
	return &this
}

// GetSubscriptions returns the Subscriptions field value
func (o *PlanFetchResponseData) GetSubscriptions() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Subscriptions
}

// GetSubscriptionsOk returns a tuple with the Subscriptions field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetSubscriptionsOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subscriptions, true
}

// SetSubscriptions sets field value
func (o *PlanFetchResponseData) SetSubscriptions(v []interface{}) {
	o.Subscriptions = v
}

// GetPages returns the Pages field value
func (o *PlanFetchResponseData) GetPages() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Pages
}

// GetPagesOk returns a tuple with the Pages field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetPagesOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pages, true
}

// SetPages sets field value
func (o *PlanFetchResponseData) SetPages(v []interface{}) {
	o.Pages = v
}

// GetDomain returns the Domain field value
func (o *PlanFetchResponseData) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *PlanFetchResponseData) SetDomain(v string) {
	o.Domain = v
}

// GetName returns the Name field value
func (o *PlanFetchResponseData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PlanFetchResponseData) SetName(v string) {
	o.Name = v
}

// GetPlanCode returns the PlanCode field value
func (o *PlanFetchResponseData) GetPlanCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanCode
}

// GetPlanCodeOk returns a tuple with the PlanCode field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetPlanCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanCode, true
}

// SetPlanCode sets field value
func (o *PlanFetchResponseData) SetPlanCode(v string) {
	o.PlanCode = v
}

// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PlanFetchResponseData) GetDescription() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlanFetchResponseData) GetDescriptionOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *PlanFetchResponseData) SetDescription(v interface{}) {
	o.Description = v
}

// GetAmount returns the Amount field value
func (o *PlanFetchResponseData) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *PlanFetchResponseData) SetAmount(v int32) {
	o.Amount = v
}

// GetInterval returns the Interval field value
func (o *PlanFetchResponseData) GetInterval() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetIntervalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Interval, true
}

// SetInterval sets field value
func (o *PlanFetchResponseData) SetInterval(v string) {
	o.Interval = v
}

// GetInvoiceLimit returns the InvoiceLimit field value
func (o *PlanFetchResponseData) GetInvoiceLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InvoiceLimit
}

// GetInvoiceLimitOk returns a tuple with the InvoiceLimit field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetInvoiceLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvoiceLimit, true
}

// SetInvoiceLimit sets field value
func (o *PlanFetchResponseData) SetInvoiceLimit(v int32) {
	o.InvoiceLimit = v
}

// GetSendInvoices returns the SendInvoices field value
func (o *PlanFetchResponseData) GetSendInvoices() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SendInvoices
}

// GetSendInvoicesOk returns a tuple with the SendInvoices field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetSendInvoicesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SendInvoices, true
}

// SetSendInvoices sets field value
func (o *PlanFetchResponseData) SetSendInvoices(v bool) {
	o.SendInvoices = v
}

// GetSendSms returns the SendSms field value
func (o *PlanFetchResponseData) GetSendSms() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SendSms
}

// GetSendSmsOk returns a tuple with the SendSms field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetSendSmsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SendSms, true
}

// SetSendSms sets field value
func (o *PlanFetchResponseData) SetSendSms(v bool) {
	o.SendSms = v
}

// GetHostedPage returns the HostedPage field value
func (o *PlanFetchResponseData) GetHostedPage() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HostedPage
}

// GetHostedPageOk returns a tuple with the HostedPage field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetHostedPageOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostedPage, true
}

// SetHostedPage sets field value
func (o *PlanFetchResponseData) SetHostedPage(v bool) {
	o.HostedPage = v
}

// GetHostedPageUrl returns the HostedPageUrl field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PlanFetchResponseData) GetHostedPageUrl() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.HostedPageUrl
}

// GetHostedPageUrlOk returns a tuple with the HostedPageUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlanFetchResponseData) GetHostedPageUrlOk() (*interface{}, bool) {
	if o == nil || IsNil(o.HostedPageUrl) {
		return nil, false
	}
	return &o.HostedPageUrl, true
}

// SetHostedPageUrl sets field value
func (o *PlanFetchResponseData) SetHostedPageUrl(v interface{}) {
	o.HostedPageUrl = v
}

// GetHostedPageSummary returns the HostedPageSummary field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PlanFetchResponseData) GetHostedPageSummary() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.HostedPageSummary
}

// GetHostedPageSummaryOk returns a tuple with the HostedPageSummary field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlanFetchResponseData) GetHostedPageSummaryOk() (*interface{}, bool) {
	if o == nil || IsNil(o.HostedPageSummary) {
		return nil, false
	}
	return &o.HostedPageSummary, true
}

// SetHostedPageSummary sets field value
func (o *PlanFetchResponseData) SetHostedPageSummary(v interface{}) {
	o.HostedPageSummary = v
}

// GetCurrency returns the Currency field value
func (o *PlanFetchResponseData) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *PlanFetchResponseData) SetCurrency(v string) {
	o.Currency = v
}

// GetMigrate returns the Migrate field value
func (o *PlanFetchResponseData) GetMigrate() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Migrate
}

// GetMigrateOk returns a tuple with the Migrate field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetMigrateOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Migrate, true
}

// SetMigrate sets field value
func (o *PlanFetchResponseData) SetMigrate(v bool) {
	o.Migrate = v
}

// GetIsDeleted returns the IsDeleted field value
func (o *PlanFetchResponseData) GetIsDeleted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetIsDeletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDeleted, true
}

// SetIsDeleted sets field value
func (o *PlanFetchResponseData) SetIsDeleted(v bool) {
	o.IsDeleted = v
}

// GetIsArchived returns the IsArchived field value
func (o *PlanFetchResponseData) GetIsArchived() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsArchived
}

// GetIsArchivedOk returns a tuple with the IsArchived field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetIsArchivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsArchived, true
}

// SetIsArchived sets field value
func (o *PlanFetchResponseData) SetIsArchived(v bool) {
	o.IsArchived = v
}

// GetId returns the Id field value
func (o *PlanFetchResponseData) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PlanFetchResponseData) SetId(v int32) {
	o.Id = v
}

// GetIntegration returns the Integration field value
func (o *PlanFetchResponseData) GetIntegration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Integration
}

// GetIntegrationOk returns a tuple with the Integration field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetIntegrationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Integration, true
}

// SetIntegration sets field value
func (o *PlanFetchResponseData) SetIntegration(v int32) {
	o.Integration = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PlanFetchResponseData) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PlanFetchResponseData) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *PlanFetchResponseData) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *PlanFetchResponseData) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetPagesCount returns the PagesCount field value
func (o *PlanFetchResponseData) GetPagesCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PagesCount
}

// GetPagesCountOk returns a tuple with the PagesCount field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetPagesCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PagesCount, true
}

// SetPagesCount sets field value
func (o *PlanFetchResponseData) SetPagesCount(v int32) {
	o.PagesCount = v
}

// GetSubscribersCount returns the SubscribersCount field value
func (o *PlanFetchResponseData) GetSubscribersCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SubscribersCount
}

// GetSubscribersCountOk returns a tuple with the SubscribersCount field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetSubscribersCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubscribersCount, true
}

// SetSubscribersCount sets field value
func (o *PlanFetchResponseData) SetSubscribersCount(v int32) {
	o.SubscribersCount = v
}

// GetSubscriptionsCount returns the SubscriptionsCount field value
func (o *PlanFetchResponseData) GetSubscriptionsCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SubscriptionsCount
}

// GetSubscriptionsCountOk returns a tuple with the SubscriptionsCount field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetSubscriptionsCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubscriptionsCount, true
}

// SetSubscriptionsCount sets field value
func (o *PlanFetchResponseData) SetSubscriptionsCount(v int32) {
	o.SubscriptionsCount = v
}

// GetActiveSubscriptionsCount returns the ActiveSubscriptionsCount field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *PlanFetchResponseData) GetActiveSubscriptionsCount() int32 {
	if o == nil || o.ActiveSubscriptionsCount.Get() == nil {
		var ret int32
		return ret
	}

	return *o.ActiveSubscriptionsCount.Get()
}

// GetActiveSubscriptionsCountOk returns a tuple with the ActiveSubscriptionsCount field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlanFetchResponseData) GetActiveSubscriptionsCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActiveSubscriptionsCount.Get(), o.ActiveSubscriptionsCount.IsSet()
}

// SetActiveSubscriptionsCount sets field value
func (o *PlanFetchResponseData) SetActiveSubscriptionsCount(v int32) {
	o.ActiveSubscriptionsCount.Set(&v)
}

// GetTotalRevenue returns the TotalRevenue field value
func (o *PlanFetchResponseData) GetTotalRevenue() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalRevenue
}

// GetTotalRevenueOk returns a tuple with the TotalRevenue field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetTotalRevenueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalRevenue, true
}

// SetTotalRevenue sets field value
func (o *PlanFetchResponseData) SetTotalRevenue(v int32) {
	o.TotalRevenue = v
}

// GetSubscribers returns the Subscribers field value
func (o *PlanFetchResponseData) GetSubscribers() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Subscribers
}

// GetSubscribersOk returns a tuple with the Subscribers field value
// and a boolean to check if the value has been set.
func (o *PlanFetchResponseData) GetSubscribersOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subscribers, true
}

// SetSubscribers sets field value
func (o *PlanFetchResponseData) SetSubscribers(v []interface{}) {
	o.Subscribers = v
}

func (o PlanFetchResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlanFetchResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subscriptions"] = o.Subscriptions
	toSerialize["pages"] = o.Pages
	toSerialize["domain"] = o.Domain
	toSerialize["name"] = o.Name
	toSerialize["plan_code"] = o.PlanCode
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	toSerialize["amount"] = o.Amount
	toSerialize["interval"] = o.Interval
	toSerialize["invoice_limit"] = o.InvoiceLimit
	toSerialize["send_invoices"] = o.SendInvoices
	toSerialize["send_sms"] = o.SendSms
	toSerialize["hosted_page"] = o.HostedPage
	if o.HostedPageUrl != nil {
		toSerialize["hosted_page_url"] = o.HostedPageUrl
	}
	if o.HostedPageSummary != nil {
		toSerialize["hosted_page_summary"] = o.HostedPageSummary
	}
	toSerialize["currency"] = o.Currency
	toSerialize["migrate"] = o.Migrate
	toSerialize["is_deleted"] = o.IsDeleted
	toSerialize["is_archived"] = o.IsArchived
	toSerialize["id"] = o.Id
	toSerialize["integration"] = o.Integration
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["pages_count"] = o.PagesCount
	toSerialize["subscribers_count"] = o.SubscribersCount
	toSerialize["subscriptions_count"] = o.SubscriptionsCount
	toSerialize["active_subscriptions_count"] = o.ActiveSubscriptionsCount.Get()
	toSerialize["total_revenue"] = o.TotalRevenue
	toSerialize["subscribers"] = o.Subscribers
	return toSerialize, nil
}

func (o *PlanFetchResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subscriptions",
		"pages",
		"domain",
		"name",
		"plan_code",
		"description",
		"amount",
		"interval",
		"invoice_limit",
		"send_invoices",
		"send_sms",
		"hosted_page",
		"hosted_page_url",
		"hosted_page_summary",
		"currency",
		"migrate",
		"is_deleted",
		"is_archived",
		"id",
		"integration",
		"createdAt",
		"updatedAt",
		"pages_count",
		"subscribers_count",
		"subscriptions_count",
		"active_subscriptions_count",
		"total_revenue",
		"subscribers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlanFetchResponseData := _PlanFetchResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlanFetchResponseData)

	if err != nil {
		return err
	}

	*o = PlanFetchResponseData(varPlanFetchResponseData)

	return err
}

type NullablePlanFetchResponseData struct {
	value *PlanFetchResponseData
	isSet bool
}

func (v NullablePlanFetchResponseData) Get() *PlanFetchResponseData {
	return v.value
}

func (v *NullablePlanFetchResponseData) Set(val *PlanFetchResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanFetchResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanFetchResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanFetchResponseData(val *PlanFetchResponseData) *NullablePlanFetchResponseData {
	return &NullablePlanFetchResponseData{value: val, isSet: true}
}

func (v NullablePlanFetchResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanFetchResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


