/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SettlementListResponseArray type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettlementListResponseArray{}

// SettlementListResponseArray struct for SettlementListResponseArray
type SettlementListResponseArray struct {
	Id int32 `json:"id"`
	Domain string `json:"domain"`
	Status string `json:"status"`
	Currency string `json:"currency"`
	Integration int32 `json:"integration"`
	TotalAmount int32 `json:"total_amount"`
	EffectiveAmount int32 `json:"effective_amount"`
	TotalFees int32 `json:"total_fees"`
	TotalProcessed int32 `json:"total_processed"`
	Deductions NullableInt32 `json:"deductions"`
	SettlementDate time.Time `json:"settlement_date"`
	SettledBy NullableString `json:"settled_by"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type _SettlementListResponseArray SettlementListResponseArray

// NewSettlementListResponseArray instantiates a new SettlementListResponseArray object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettlementListResponseArray(id int32, domain string, status string, currency string, integration int32, totalAmount int32, effectiveAmount int32, totalFees int32, totalProcessed int32, deductions NullableInt32, settlementDate time.Time, settledBy NullableString, createdAt time.Time, updatedAt time.Time) *SettlementListResponseArray {
	this := SettlementListResponseArray{}
	this.Id = id
	this.Domain = domain
	this.Status = status
	this.Currency = currency
	this.Integration = integration
	this.TotalAmount = totalAmount
	this.EffectiveAmount = effectiveAmount
	this.TotalFees = totalFees
	this.TotalProcessed = totalProcessed
	this.Deductions = deductions
	this.SettlementDate = settlementDate
	this.SettledBy = settledBy
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewSettlementListResponseArrayWithDefaults instantiates a new SettlementListResponseArray object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettlementListResponseArrayWithDefaults() *SettlementListResponseArray {
	this := SettlementListResponseArray{}
	return &this
}

// GetId returns the Id field value
func (o *SettlementListResponseArray) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SettlementListResponseArray) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SettlementListResponseArray) SetId(v int32) {
	o.Id = v
}

// GetDomain returns the Domain field value
func (o *SettlementListResponseArray) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *SettlementListResponseArray) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *SettlementListResponseArray) SetDomain(v string) {
	o.Domain = v
}

// GetStatus returns the Status field value
func (o *SettlementListResponseArray) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SettlementListResponseArray) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SettlementListResponseArray) SetStatus(v string) {
	o.Status = v
}

// GetCurrency returns the Currency field value
func (o *SettlementListResponseArray) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *SettlementListResponseArray) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *SettlementListResponseArray) SetCurrency(v string) {
	o.Currency = v
}

// GetIntegration returns the Integration field value
func (o *SettlementListResponseArray) GetIntegration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Integration
}

// GetIntegrationOk returns a tuple with the Integration field value
// and a boolean to check if the value has been set.
func (o *SettlementListResponseArray) GetIntegrationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Integration, true
}

// SetIntegration sets field value
func (o *SettlementListResponseArray) SetIntegration(v int32) {
	o.Integration = v
}

// GetTotalAmount returns the TotalAmount field value
func (o *SettlementListResponseArray) GetTotalAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalAmount
}

// GetTotalAmountOk returns a tuple with the TotalAmount field value
// and a boolean to check if the value has been set.
func (o *SettlementListResponseArray) GetTotalAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalAmount, true
}

// SetTotalAmount sets field value
func (o *SettlementListResponseArray) SetTotalAmount(v int32) {
	o.TotalAmount = v
}

// GetEffectiveAmount returns the EffectiveAmount field value
func (o *SettlementListResponseArray) GetEffectiveAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EffectiveAmount
}

// GetEffectiveAmountOk returns a tuple with the EffectiveAmount field value
// and a boolean to check if the value has been set.
func (o *SettlementListResponseArray) GetEffectiveAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EffectiveAmount, true
}

// SetEffectiveAmount sets field value
func (o *SettlementListResponseArray) SetEffectiveAmount(v int32) {
	o.EffectiveAmount = v
}

// GetTotalFees returns the TotalFees field value
func (o *SettlementListResponseArray) GetTotalFees() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalFees
}

// GetTotalFeesOk returns a tuple with the TotalFees field value
// and a boolean to check if the value has been set.
func (o *SettlementListResponseArray) GetTotalFeesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalFees, true
}

// SetTotalFees sets field value
func (o *SettlementListResponseArray) SetTotalFees(v int32) {
	o.TotalFees = v
}

// GetTotalProcessed returns the TotalProcessed field value
func (o *SettlementListResponseArray) GetTotalProcessed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalProcessed
}

// GetTotalProcessedOk returns a tuple with the TotalProcessed field value
// and a boolean to check if the value has been set.
func (o *SettlementListResponseArray) GetTotalProcessedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalProcessed, true
}

// SetTotalProcessed sets field value
func (o *SettlementListResponseArray) SetTotalProcessed(v int32) {
	o.TotalProcessed = v
}

// GetDeductions returns the Deductions field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *SettlementListResponseArray) GetDeductions() int32 {
	if o == nil || o.Deductions.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Deductions.Get()
}

// GetDeductionsOk returns a tuple with the Deductions field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SettlementListResponseArray) GetDeductionsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Deductions.Get(), o.Deductions.IsSet()
}

// SetDeductions sets field value
func (o *SettlementListResponseArray) SetDeductions(v int32) {
	o.Deductions.Set(&v)
}

// GetSettlementDate returns the SettlementDate field value
func (o *SettlementListResponseArray) GetSettlementDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.SettlementDate
}

// GetSettlementDateOk returns a tuple with the SettlementDate field value
// and a boolean to check if the value has been set.
func (o *SettlementListResponseArray) GetSettlementDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettlementDate, true
}

// SetSettlementDate sets field value
func (o *SettlementListResponseArray) SetSettlementDate(v time.Time) {
	o.SettlementDate = v
}

// GetSettledBy returns the SettledBy field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SettlementListResponseArray) GetSettledBy() string {
	if o == nil || o.SettledBy.Get() == nil {
		var ret string
		return ret
	}

	return *o.SettledBy.Get()
}

// GetSettledByOk returns a tuple with the SettledBy field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SettlementListResponseArray) GetSettledByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SettledBy.Get(), o.SettledBy.IsSet()
}

// SetSettledBy sets field value
func (o *SettlementListResponseArray) SetSettledBy(v string) {
	o.SettledBy.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *SettlementListResponseArray) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SettlementListResponseArray) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SettlementListResponseArray) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *SettlementListResponseArray) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *SettlementListResponseArray) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *SettlementListResponseArray) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o SettlementListResponseArray) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettlementListResponseArray) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["domain"] = o.Domain
	toSerialize["status"] = o.Status
	toSerialize["currency"] = o.Currency
	toSerialize["integration"] = o.Integration
	toSerialize["total_amount"] = o.TotalAmount
	toSerialize["effective_amount"] = o.EffectiveAmount
	toSerialize["total_fees"] = o.TotalFees
	toSerialize["total_processed"] = o.TotalProcessed
	toSerialize["deductions"] = o.Deductions.Get()
	toSerialize["settlement_date"] = o.SettlementDate
	toSerialize["settled_by"] = o.SettledBy.Get()
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *SettlementListResponseArray) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"domain",
		"status",
		"currency",
		"integration",
		"total_amount",
		"effective_amount",
		"total_fees",
		"total_processed",
		"deductions",
		"settlement_date",
		"settled_by",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSettlementListResponseArray := _SettlementListResponseArray{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSettlementListResponseArray)

	if err != nil {
		return err
	}

	*o = SettlementListResponseArray(varSettlementListResponseArray)

	return err
}

type NullableSettlementListResponseArray struct {
	value *SettlementListResponseArray
	isSet bool
}

func (v NullableSettlementListResponseArray) Get() *SettlementListResponseArray {
	return v.value
}

func (v *NullableSettlementListResponseArray) Set(val *SettlementListResponseArray) {
	v.value = val
	v.isSet = true
}

func (v NullableSettlementListResponseArray) IsSet() bool {
	return v.isSet
}

func (v *NullableSettlementListResponseArray) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettlementListResponseArray(val *SettlementListResponseArray) *NullableSettlementListResponseArray {
	return &NullableSettlementListResponseArray{value: val, isSet: true}
}

func (v NullableSettlementListResponseArray) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettlementListResponseArray) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


