/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
)

// checks if the TransferRecipientListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransferRecipientListResponse{}

// TransferRecipientListResponse struct for TransferRecipientListResponse
type TransferRecipientListResponse struct {
	Status bool `json:"status"`
	Message string `json:"message"`
	Data []TransferRecipientListResponseArray `json:"data"`
	Meta SubaccountListResponseMeta `json:"meta"`
}

// NewTransferRecipientListResponse instantiates a new TransferRecipientListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferRecipientListResponse(status bool, message string, data []TransferRecipientListResponseArray, meta SubaccountListResponseMeta) *TransferRecipientListResponse {
	this := TransferRecipientListResponse{}
	this.Status = status
	this.Message = message
	this.Data = data
	this.Meta = meta
	return &this
}

// NewTransferRecipientListResponseWithDefaults instantiates a new TransferRecipientListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferRecipientListResponseWithDefaults() *TransferRecipientListResponse {
	this := TransferRecipientListResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *TransferRecipientListResponse) GetStatus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TransferRecipientListResponse) GetStatusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TransferRecipientListResponse) SetStatus(v bool) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *TransferRecipientListResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *TransferRecipientListResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *TransferRecipientListResponse) SetMessage(v string) {
	o.Message = v
}

// GetData returns the Data field value
func (o *TransferRecipientListResponse) GetData() []TransferRecipientListResponseArray {
	if o == nil {
		var ret []TransferRecipientListResponseArray
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *TransferRecipientListResponse) GetDataOk() ([]TransferRecipientListResponseArray, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *TransferRecipientListResponse) SetData(v []TransferRecipientListResponseArray) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *TransferRecipientListResponse) GetMeta() SubaccountListResponseMeta {
	if o == nil {
		var ret SubaccountListResponseMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *TransferRecipientListResponse) GetMetaOk() (*SubaccountListResponseMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *TransferRecipientListResponse) SetMeta(v SubaccountListResponseMeta) {
	o.Meta = v
}

func (o TransferRecipientListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransferRecipientListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	toSerialize["data"] = o.Data
	toSerialize["meta"] = o.Meta
	return toSerialize, nil
}

type NullableTransferRecipientListResponse struct {
	value *TransferRecipientListResponse
	isSet bool
}

func (v NullableTransferRecipientListResponse) Get() *TransferRecipientListResponse {
	return v.value
}

func (v *NullableTransferRecipientListResponse) Set(val *TransferRecipientListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferRecipientListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferRecipientListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferRecipientListResponse(val *TransferRecipientListResponse) *NullableTransferRecipientListResponse {
	return &NullableTransferRecipientListResponse{value: val, isSet: true}
}

func (v NullableTransferRecipientListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferRecipientListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


