/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
)

// checks if the CustomerInitializeDirectDebitResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerInitializeDirectDebitResponse{}

// CustomerInitializeDirectDebitResponse struct for CustomerInitializeDirectDebitResponse
type CustomerInitializeDirectDebitResponse struct {
	Status bool `json:"status"`
	Message string `json:"message"`
	Data CustomerInitializeDirectDebitResponseData `json:"data"`
}

// NewCustomerInitializeDirectDebitResponse instantiates a new CustomerInitializeDirectDebitResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerInitializeDirectDebitResponse(status bool, message string, data CustomerInitializeDirectDebitResponseData) *CustomerInitializeDirectDebitResponse {
	this := CustomerInitializeDirectDebitResponse{}
	this.Status = status
	this.Message = message
	this.Data = data
	return &this
}

// NewCustomerInitializeDirectDebitResponseWithDefaults instantiates a new CustomerInitializeDirectDebitResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerInitializeDirectDebitResponseWithDefaults() *CustomerInitializeDirectDebitResponse {
	this := CustomerInitializeDirectDebitResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *CustomerInitializeDirectDebitResponse) GetStatus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CustomerInitializeDirectDebitResponse) GetStatusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CustomerInitializeDirectDebitResponse) SetStatus(v bool) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *CustomerInitializeDirectDebitResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *CustomerInitializeDirectDebitResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *CustomerInitializeDirectDebitResponse) SetMessage(v string) {
	o.Message = v
}

// GetData returns the Data field value
func (o *CustomerInitializeDirectDebitResponse) GetData() CustomerInitializeDirectDebitResponseData {
	if o == nil {
		var ret CustomerInitializeDirectDebitResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CustomerInitializeDirectDebitResponse) GetDataOk() (*CustomerInitializeDirectDebitResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CustomerInitializeDirectDebitResponse) SetData(v CustomerInitializeDirectDebitResponseData) {
	o.Data = v
}

func (o CustomerInitializeDirectDebitResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerInitializeDirectDebitResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableCustomerInitializeDirectDebitResponse struct {
	value *CustomerInitializeDirectDebitResponse
	isSet bool
}

func (v NullableCustomerInitializeDirectDebitResponse) Get() *CustomerInitializeDirectDebitResponse {
	return v.value
}

func (v *NullableCustomerInitializeDirectDebitResponse) Set(val *CustomerInitializeDirectDebitResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerInitializeDirectDebitResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerInitializeDirectDebitResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerInitializeDirectDebitResponse(val *CustomerInitializeDirectDebitResponse) *NullableCustomerInitializeDirectDebitResponse {
	return &NullableCustomerInitializeDirectDebitResponse{value: val, isSet: true}
}

func (v NullableCustomerInitializeDirectDebitResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerInitializeDirectDebitResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


