/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
)

// checks if the BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata{}

// BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata struct for BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata
type BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata struct {
	CallingCode *string `json:"calling_code,omitempty"`
}

// NewBulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata instantiates a new BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata() *BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata {
	this := BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata{}
	return &this
}

// NewBulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadataWithDefaults instantiates a new BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadataWithDefaults() *BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata {
	this := BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata{}
	return &this
}

// GetCallingCode returns the CallingCode field value if set, zero value otherwise.
func (o *BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata) GetCallingCode() string {
	if o == nil || IsNil(o.CallingCode) {
		var ret string
		return ret
	}
	return *o.CallingCode
}

// GetCallingCodeOk returns a tuple with the CallingCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata) GetCallingCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CallingCode) {
		return nil, false
	}
	return o.CallingCode, true
}

// HasCallingCode returns a boolean if a field has been set.
func (o *BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata) HasCallingCode() bool {
	if o != nil && !IsNil(o.CallingCode) {
		return true
	}

	return false
}

// SetCallingCode gets a reference to the given string and assigns it to the CallingCode field.
func (o *BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata) SetCallingCode(v string) {
	o.CallingCode = &v
}

func (o BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CallingCode) {
		toSerialize["calling_code"] = o.CallingCode
	}
	return toSerialize, nil
}

type NullableBulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata struct {
	value *BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata
	isSet bool
}

func (v NullableBulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata) Get() *BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata {
	return v.value
}

func (v *NullableBulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata) Set(val *BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata(val *BulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata) *NullableBulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata {
	return &NullableBulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata{value: val, isSet: true}
}

func (v NullableBulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkChargeFetchBulkBatchChargesResponseArrayCustomerMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


