/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
)

// checks if the ChargeAuthorizationResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChargeAuthorizationResponseData{}

// ChargeAuthorizationResponseData struct for ChargeAuthorizationResponseData
type ChargeAuthorizationResponseData struct {
	Amount int32 `json:"amount"`
	Currency string `json:"currency"`
	TransactionDate string `json:"transaction_date"`
	Status string `json:"status"`
	Reference string `json:"reference"`
	Domain string `json:"domain"`
	Metadata string `json:"metadata"`
	GatewayResponse string `json:"gateway_response"`
	Message NullableString `json:"message"`
	Channel string `json:"channel"`
	IpAddress map[string]interface{} `json:"ip_address"`
	Log NullableChargeAuthorizationResponseDataLog `json:"log"`
	Fees NullableInt32 `json:"fees"`
	Authorization ChargeAuthorizationResponseDataAuthorization `json:"authorization"`
	Customer ChargeAuthorizationResponseDataCustomer `json:"customer"`
	Plan map[string]interface{} `json:"plan"`
	Id int32 `json:"id"`
}

// NewChargeAuthorizationResponseData instantiates a new ChargeAuthorizationResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChargeAuthorizationResponseData(amount int32, currency string, transactionDate string, status string, reference string, domain string, metadata string, gatewayResponse string, message NullableString, channel string, ipAddress map[string]interface{}, log NullableChargeAuthorizationResponseDataLog, fees NullableInt32, authorization ChargeAuthorizationResponseDataAuthorization, customer ChargeAuthorizationResponseDataCustomer, plan map[string]interface{}, id int32) *ChargeAuthorizationResponseData {
	this := ChargeAuthorizationResponseData{}
	this.Amount = amount
	this.Currency = currency
	this.TransactionDate = transactionDate
	this.Status = status
	this.Reference = reference
	this.Domain = domain
	this.Metadata = metadata
	this.GatewayResponse = gatewayResponse
	this.Message = message
	this.Channel = channel
	this.IpAddress = ipAddress
	this.Log = log
	this.Fees = fees
	this.Authorization = authorization
	this.Customer = customer
	this.Plan = plan
	this.Id = id
	return &this
}

// NewChargeAuthorizationResponseDataWithDefaults instantiates a new ChargeAuthorizationResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChargeAuthorizationResponseDataWithDefaults() *ChargeAuthorizationResponseData {
	this := ChargeAuthorizationResponseData{}
	return &this
}

// GetAmount returns the Amount field value
func (o *ChargeAuthorizationResponseData) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *ChargeAuthorizationResponseData) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *ChargeAuthorizationResponseData) SetAmount(v int32) {
	o.Amount = v
}

// GetCurrency returns the Currency field value
func (o *ChargeAuthorizationResponseData) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *ChargeAuthorizationResponseData) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *ChargeAuthorizationResponseData) SetCurrency(v string) {
	o.Currency = v
}

// GetTransactionDate returns the TransactionDate field value
func (o *ChargeAuthorizationResponseData) GetTransactionDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionDate
}

// GetTransactionDateOk returns a tuple with the TransactionDate field value
// and a boolean to check if the value has been set.
func (o *ChargeAuthorizationResponseData) GetTransactionDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionDate, true
}

// SetTransactionDate sets field value
func (o *ChargeAuthorizationResponseData) SetTransactionDate(v string) {
	o.TransactionDate = v
}

// GetStatus returns the Status field value
func (o *ChargeAuthorizationResponseData) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ChargeAuthorizationResponseData) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ChargeAuthorizationResponseData) SetStatus(v string) {
	o.Status = v
}

// GetReference returns the Reference field value
func (o *ChargeAuthorizationResponseData) GetReference() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value
// and a boolean to check if the value has been set.
func (o *ChargeAuthorizationResponseData) GetReferenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reference, true
}

// SetReference sets field value
func (o *ChargeAuthorizationResponseData) SetReference(v string) {
	o.Reference = v
}

// GetDomain returns the Domain field value
func (o *ChargeAuthorizationResponseData) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *ChargeAuthorizationResponseData) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *ChargeAuthorizationResponseData) SetDomain(v string) {
	o.Domain = v
}

// GetMetadata returns the Metadata field value
func (o *ChargeAuthorizationResponseData) GetMetadata() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *ChargeAuthorizationResponseData) GetMetadataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *ChargeAuthorizationResponseData) SetMetadata(v string) {
	o.Metadata = v
}

// GetGatewayResponse returns the GatewayResponse field value
func (o *ChargeAuthorizationResponseData) GetGatewayResponse() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GatewayResponse
}

// GetGatewayResponseOk returns a tuple with the GatewayResponse field value
// and a boolean to check if the value has been set.
func (o *ChargeAuthorizationResponseData) GetGatewayResponseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GatewayResponse, true
}

// SetGatewayResponse sets field value
func (o *ChargeAuthorizationResponseData) SetGatewayResponse(v string) {
	o.GatewayResponse = v
}

// GetMessage returns the Message field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ChargeAuthorizationResponseData) GetMessage() string {
	if o == nil || o.Message.Get() == nil {
		var ret string
		return ret
	}

	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChargeAuthorizationResponseData) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// SetMessage sets field value
func (o *ChargeAuthorizationResponseData) SetMessage(v string) {
	o.Message.Set(&v)
}

// GetChannel returns the Channel field value
func (o *ChargeAuthorizationResponseData) GetChannel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Channel
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
func (o *ChargeAuthorizationResponseData) GetChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Channel, true
}

// SetChannel sets field value
func (o *ChargeAuthorizationResponseData) SetChannel(v string) {
	o.Channel = v
}

// GetIpAddress returns the IpAddress field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *ChargeAuthorizationResponseData) GetIpAddress() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChargeAuthorizationResponseData) GetIpAddressOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.IpAddress) {
		return map[string]interface{}{}, false
	}
	return o.IpAddress, true
}

// SetIpAddress sets field value
func (o *ChargeAuthorizationResponseData) SetIpAddress(v map[string]interface{}) {
	o.IpAddress = v
}

// GetLog returns the Log field value
// If the value is explicit nil, the zero value for ChargeAuthorizationResponseDataLog will be returned
func (o *ChargeAuthorizationResponseData) GetLog() ChargeAuthorizationResponseDataLog {
	if o == nil || o.Log.Get() == nil {
		var ret ChargeAuthorizationResponseDataLog
		return ret
	}

	return *o.Log.Get()
}

// GetLogOk returns a tuple with the Log field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChargeAuthorizationResponseData) GetLogOk() (*ChargeAuthorizationResponseDataLog, bool) {
	if o == nil {
		return nil, false
	}
	return o.Log.Get(), o.Log.IsSet()
}

// SetLog sets field value
func (o *ChargeAuthorizationResponseData) SetLog(v ChargeAuthorizationResponseDataLog) {
	o.Log.Set(&v)
}

// GetFees returns the Fees field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *ChargeAuthorizationResponseData) GetFees() int32 {
	if o == nil || o.Fees.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Fees.Get()
}

// GetFeesOk returns a tuple with the Fees field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChargeAuthorizationResponseData) GetFeesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fees.Get(), o.Fees.IsSet()
}

// SetFees sets field value
func (o *ChargeAuthorizationResponseData) SetFees(v int32) {
	o.Fees.Set(&v)
}

// GetAuthorization returns the Authorization field value
func (o *ChargeAuthorizationResponseData) GetAuthorization() ChargeAuthorizationResponseDataAuthorization {
	if o == nil {
		var ret ChargeAuthorizationResponseDataAuthorization
		return ret
	}

	return o.Authorization
}

// GetAuthorizationOk returns a tuple with the Authorization field value
// and a boolean to check if the value has been set.
func (o *ChargeAuthorizationResponseData) GetAuthorizationOk() (*ChargeAuthorizationResponseDataAuthorization, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Authorization, true
}

// SetAuthorization sets field value
func (o *ChargeAuthorizationResponseData) SetAuthorization(v ChargeAuthorizationResponseDataAuthorization) {
	o.Authorization = v
}

// GetCustomer returns the Customer field value
func (o *ChargeAuthorizationResponseData) GetCustomer() ChargeAuthorizationResponseDataCustomer {
	if o == nil {
		var ret ChargeAuthorizationResponseDataCustomer
		return ret
	}

	return o.Customer
}

// GetCustomerOk returns a tuple with the Customer field value
// and a boolean to check if the value has been set.
func (o *ChargeAuthorizationResponseData) GetCustomerOk() (*ChargeAuthorizationResponseDataCustomer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Customer, true
}

// SetCustomer sets field value
func (o *ChargeAuthorizationResponseData) SetCustomer(v ChargeAuthorizationResponseDataCustomer) {
	o.Customer = v
}

// GetPlan returns the Plan field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *ChargeAuthorizationResponseData) GetPlan() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Plan
}

// GetPlanOk returns a tuple with the Plan field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChargeAuthorizationResponseData) GetPlanOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Plan) {
		return map[string]interface{}{}, false
	}
	return o.Plan, true
}

// SetPlan sets field value
func (o *ChargeAuthorizationResponseData) SetPlan(v map[string]interface{}) {
	o.Plan = v
}

// GetId returns the Id field value
func (o *ChargeAuthorizationResponseData) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ChargeAuthorizationResponseData) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ChargeAuthorizationResponseData) SetId(v int32) {
	o.Id = v
}

func (o ChargeAuthorizationResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChargeAuthorizationResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount"] = o.Amount
	toSerialize["currency"] = o.Currency
	toSerialize["transaction_date"] = o.TransactionDate
	toSerialize["status"] = o.Status
	toSerialize["reference"] = o.Reference
	toSerialize["domain"] = o.Domain
	toSerialize["metadata"] = o.Metadata
	toSerialize["gateway_response"] = o.GatewayResponse
	toSerialize["message"] = o.Message.Get()
	toSerialize["channel"] = o.Channel
	if o.IpAddress != nil {
		toSerialize["ip_address"] = o.IpAddress
	}
	toSerialize["log"] = o.Log.Get()
	toSerialize["fees"] = o.Fees.Get()
	toSerialize["authorization"] = o.Authorization
	toSerialize["customer"] = o.Customer
	if o.Plan != nil {
		toSerialize["plan"] = o.Plan
	}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableChargeAuthorizationResponseData struct {
	value *ChargeAuthorizationResponseData
	isSet bool
}

func (v NullableChargeAuthorizationResponseData) Get() *ChargeAuthorizationResponseData {
	return v.value
}

func (v *NullableChargeAuthorizationResponseData) Set(val *ChargeAuthorizationResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableChargeAuthorizationResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableChargeAuthorizationResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChargeAuthorizationResponseData(val *ChargeAuthorizationResponseData) *NullableChargeAuthorizationResponseData {
	return &NullableChargeAuthorizationResponseData{value: val, isSet: true}
}

func (v NullableChargeAuthorizationResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChargeAuthorizationResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


