/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaymentRequestTaxArray type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentRequestTaxArray{}

// PaymentRequestTaxArray struct for PaymentRequestTaxArray
type PaymentRequestTaxArray struct {
	Name string `json:"name"`
	Amount int32 `json:"amount"`
}

type _PaymentRequestTaxArray PaymentRequestTaxArray

// NewPaymentRequestTaxArray instantiates a new PaymentRequestTaxArray object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentRequestTaxArray(name string, amount int32) *PaymentRequestTaxArray {
	this := PaymentRequestTaxArray{}
	this.Name = name
	this.Amount = amount
	return &this
}

// NewPaymentRequestTaxArrayWithDefaults instantiates a new PaymentRequestTaxArray object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentRequestTaxArrayWithDefaults() *PaymentRequestTaxArray {
	this := PaymentRequestTaxArray{}
	return &this
}

// GetName returns the Name field value
func (o *PaymentRequestTaxArray) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestTaxArray) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PaymentRequestTaxArray) SetName(v string) {
	o.Name = v
}

// GetAmount returns the Amount field value
func (o *PaymentRequestTaxArray) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestTaxArray) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *PaymentRequestTaxArray) SetAmount(v int32) {
	o.Amount = v
}

func (o PaymentRequestTaxArray) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentRequestTaxArray) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["amount"] = o.Amount
	return toSerialize, nil
}

func (o *PaymentRequestTaxArray) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentRequestTaxArray := _PaymentRequestTaxArray{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaymentRequestTaxArray)

	if err != nil {
		return err
	}

	*o = PaymentRequestTaxArray(varPaymentRequestTaxArray)

	return err
}

type NullablePaymentRequestTaxArray struct {
	value *PaymentRequestTaxArray
	isSet bool
}

func (v NullablePaymentRequestTaxArray) Get() *PaymentRequestTaxArray {
	return v.value
}

func (v *NullablePaymentRequestTaxArray) Set(val *PaymentRequestTaxArray) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentRequestTaxArray) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentRequestTaxArray) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentRequestTaxArray(val *PaymentRequestTaxArray) *NullablePaymentRequestTaxArray {
	return &NullablePaymentRequestTaxArray{value: val, isSet: true}
}

func (v NullablePaymentRequestTaxArray) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentRequestTaxArray) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


