/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
)

// checks if the RefundCreateResponseDataTransactionAuthorization type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefundCreateResponseDataTransactionAuthorization{}

// RefundCreateResponseDataTransactionAuthorization struct for RefundCreateResponseDataTransactionAuthorization
type RefundCreateResponseDataTransactionAuthorization struct {
	ExpMonth map[string]interface{} `json:"exp_month"`
	ExpYear map[string]interface{} `json:"exp_year"`
	AccountName map[string]interface{} `json:"account_name"`
}

// NewRefundCreateResponseDataTransactionAuthorization instantiates a new RefundCreateResponseDataTransactionAuthorization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefundCreateResponseDataTransactionAuthorization(expMonth map[string]interface{}, expYear map[string]interface{}, accountName map[string]interface{}) *RefundCreateResponseDataTransactionAuthorization {
	this := RefundCreateResponseDataTransactionAuthorization{}
	this.ExpMonth = expMonth
	this.ExpYear = expYear
	this.AccountName = accountName
	return &this
}

// NewRefundCreateResponseDataTransactionAuthorizationWithDefaults instantiates a new RefundCreateResponseDataTransactionAuthorization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefundCreateResponseDataTransactionAuthorizationWithDefaults() *RefundCreateResponseDataTransactionAuthorization {
	this := RefundCreateResponseDataTransactionAuthorization{}
	return &this
}

// GetExpMonth returns the ExpMonth field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *RefundCreateResponseDataTransactionAuthorization) GetExpMonth() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ExpMonth
}

// GetExpMonthOk returns a tuple with the ExpMonth field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RefundCreateResponseDataTransactionAuthorization) GetExpMonthOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ExpMonth) {
		return map[string]interface{}{}, false
	}
	return o.ExpMonth, true
}

// SetExpMonth sets field value
func (o *RefundCreateResponseDataTransactionAuthorization) SetExpMonth(v map[string]interface{}) {
	o.ExpMonth = v
}

// GetExpYear returns the ExpYear field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *RefundCreateResponseDataTransactionAuthorization) GetExpYear() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ExpYear
}

// GetExpYearOk returns a tuple with the ExpYear field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RefundCreateResponseDataTransactionAuthorization) GetExpYearOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ExpYear) {
		return map[string]interface{}{}, false
	}
	return o.ExpYear, true
}

// SetExpYear sets field value
func (o *RefundCreateResponseDataTransactionAuthorization) SetExpYear(v map[string]interface{}) {
	o.ExpYear = v
}

// GetAccountName returns the AccountName field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *RefundCreateResponseDataTransactionAuthorization) GetAccountName() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.AccountName
}

// GetAccountNameOk returns a tuple with the AccountName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RefundCreateResponseDataTransactionAuthorization) GetAccountNameOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AccountName) {
		return map[string]interface{}{}, false
	}
	return o.AccountName, true
}

// SetAccountName sets field value
func (o *RefundCreateResponseDataTransactionAuthorization) SetAccountName(v map[string]interface{}) {
	o.AccountName = v
}

func (o RefundCreateResponseDataTransactionAuthorization) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefundCreateResponseDataTransactionAuthorization) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ExpMonth != nil {
		toSerialize["exp_month"] = o.ExpMonth
	}
	if o.ExpYear != nil {
		toSerialize["exp_year"] = o.ExpYear
	}
	if o.AccountName != nil {
		toSerialize["account_name"] = o.AccountName
	}
	return toSerialize, nil
}

type NullableRefundCreateResponseDataTransactionAuthorization struct {
	value *RefundCreateResponseDataTransactionAuthorization
	isSet bool
}

func (v NullableRefundCreateResponseDataTransactionAuthorization) Get() *RefundCreateResponseDataTransactionAuthorization {
	return v.value
}

func (v *NullableRefundCreateResponseDataTransactionAuthorization) Set(val *RefundCreateResponseDataTransactionAuthorization) {
	v.value = val
	v.isSet = true
}

func (v NullableRefundCreateResponseDataTransactionAuthorization) IsSet() bool {
	return v.isSet
}

func (v *NullableRefundCreateResponseDataTransactionAuthorization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefundCreateResponseDataTransactionAuthorization(val *RefundCreateResponseDataTransactionAuthorization) *NullableRefundCreateResponseDataTransactionAuthorization {
	return &NullableRefundCreateResponseDataTransactionAuthorization{value: val, isSet: true}
}

func (v NullableRefundCreateResponseDataTransactionAuthorization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefundCreateResponseDataTransactionAuthorization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


