/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaymentRequestFinalizeResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentRequestFinalizeResponseData{}

// PaymentRequestFinalizeResponseData struct for PaymentRequestFinalizeResponseData
type PaymentRequestFinalizeResponseData struct {
	Id int32 `json:"id"`
	Domain string `json:"domain"`
	Amount int32 `json:"amount"`
	Currency string `json:"currency"`
	DueDate NullableString `json:"due_date"`
	HasInvoice bool `json:"has_invoice"`
	InvoiceNumber NullableInt32 `json:"invoice_number"`
	Description NullableString `json:"description"`
	PdfUrl NullableString `json:"pdf_url"`
	LineItems []PaymentRequestLineItemsArray `json:"line_items"`
	Tax []PaymentRequestTaxArray `json:"tax"`
	RequestCode string `json:"request_code"`
	Status string `json:"status"`
	Paid bool `json:"paid"`
	PaidAt NullableString `json:"paid_at"`
	Metadata map[string]interface{} `json:"metadata"`
	Notifications []interface{} `json:"notifications"`
	OfflineReference string `json:"offline_reference"`
	Customer DedicatedNubanCreateResponseDataCustomer `json:"customer"`
	CreatedAt string `json:"created_at"`
	Discount NullablePaymentRequestFinalizeResponseDataDiscount `json:"discount,omitempty"`
	SplitCode NullableString `json:"split_code,omitempty"`
	PendingAmount int32 `json:"pending_amount"`
}

type _PaymentRequestFinalizeResponseData PaymentRequestFinalizeResponseData

// NewPaymentRequestFinalizeResponseData instantiates a new PaymentRequestFinalizeResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentRequestFinalizeResponseData(id int32, domain string, amount int32, currency string, dueDate NullableString, hasInvoice bool, invoiceNumber NullableInt32, description NullableString, pdfUrl NullableString, lineItems []PaymentRequestLineItemsArray, tax []PaymentRequestTaxArray, requestCode string, status string, paid bool, paidAt NullableString, metadata map[string]interface{}, notifications []interface{}, offlineReference string, customer DedicatedNubanCreateResponseDataCustomer, createdAt string, pendingAmount int32) *PaymentRequestFinalizeResponseData {
	this := PaymentRequestFinalizeResponseData{}
	this.Id = id
	this.Domain = domain
	this.Amount = amount
	this.Currency = currency
	this.DueDate = dueDate
	this.HasInvoice = hasInvoice
	this.InvoiceNumber = invoiceNumber
	this.Description = description
	this.PdfUrl = pdfUrl
	this.LineItems = lineItems
	this.Tax = tax
	this.RequestCode = requestCode
	this.Status = status
	this.Paid = paid
	this.PaidAt = paidAt
	this.Metadata = metadata
	this.Notifications = notifications
	this.OfflineReference = offlineReference
	this.Customer = customer
	this.CreatedAt = createdAt
	this.PendingAmount = pendingAmount
	return &this
}

// NewPaymentRequestFinalizeResponseDataWithDefaults instantiates a new PaymentRequestFinalizeResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentRequestFinalizeResponseDataWithDefaults() *PaymentRequestFinalizeResponseData {
	this := PaymentRequestFinalizeResponseData{}
	return &this
}

// GetId returns the Id field value
func (o *PaymentRequestFinalizeResponseData) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestFinalizeResponseData) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PaymentRequestFinalizeResponseData) SetId(v int32) {
	o.Id = v
}

// GetDomain returns the Domain field value
func (o *PaymentRequestFinalizeResponseData) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestFinalizeResponseData) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *PaymentRequestFinalizeResponseData) SetDomain(v string) {
	o.Domain = v
}

// GetAmount returns the Amount field value
func (o *PaymentRequestFinalizeResponseData) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestFinalizeResponseData) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *PaymentRequestFinalizeResponseData) SetAmount(v int32) {
	o.Amount = v
}

// GetCurrency returns the Currency field value
func (o *PaymentRequestFinalizeResponseData) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestFinalizeResponseData) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *PaymentRequestFinalizeResponseData) SetCurrency(v string) {
	o.Currency = v
}

// GetDueDate returns the DueDate field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PaymentRequestFinalizeResponseData) GetDueDate() string {
	if o == nil || o.DueDate.Get() == nil {
		var ret string
		return ret
	}

	return *o.DueDate.Get()
}

// GetDueDateOk returns a tuple with the DueDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentRequestFinalizeResponseData) GetDueDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DueDate.Get(), o.DueDate.IsSet()
}

// SetDueDate sets field value
func (o *PaymentRequestFinalizeResponseData) SetDueDate(v string) {
	o.DueDate.Set(&v)
}

// GetHasInvoice returns the HasInvoice field value
func (o *PaymentRequestFinalizeResponseData) GetHasInvoice() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasInvoice
}

// GetHasInvoiceOk returns a tuple with the HasInvoice field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestFinalizeResponseData) GetHasInvoiceOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasInvoice, true
}

// SetHasInvoice sets field value
func (o *PaymentRequestFinalizeResponseData) SetHasInvoice(v bool) {
	o.HasInvoice = v
}

// GetInvoiceNumber returns the InvoiceNumber field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *PaymentRequestFinalizeResponseData) GetInvoiceNumber() int32 {
	if o == nil || o.InvoiceNumber.Get() == nil {
		var ret int32
		return ret
	}

	return *o.InvoiceNumber.Get()
}

// GetInvoiceNumberOk returns a tuple with the InvoiceNumber field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentRequestFinalizeResponseData) GetInvoiceNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.InvoiceNumber.Get(), o.InvoiceNumber.IsSet()
}

// SetInvoiceNumber sets field value
func (o *PaymentRequestFinalizeResponseData) SetInvoiceNumber(v int32) {
	o.InvoiceNumber.Set(&v)
}

// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PaymentRequestFinalizeResponseData) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}

	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentRequestFinalizeResponseData) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// SetDescription sets field value
func (o *PaymentRequestFinalizeResponseData) SetDescription(v string) {
	o.Description.Set(&v)
}

// GetPdfUrl returns the PdfUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PaymentRequestFinalizeResponseData) GetPdfUrl() string {
	if o == nil || o.PdfUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.PdfUrl.Get()
}

// GetPdfUrlOk returns a tuple with the PdfUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentRequestFinalizeResponseData) GetPdfUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PdfUrl.Get(), o.PdfUrl.IsSet()
}

// SetPdfUrl sets field value
func (o *PaymentRequestFinalizeResponseData) SetPdfUrl(v string) {
	o.PdfUrl.Set(&v)
}

// GetLineItems returns the LineItems field value
func (o *PaymentRequestFinalizeResponseData) GetLineItems() []PaymentRequestLineItemsArray {
	if o == nil {
		var ret []PaymentRequestLineItemsArray
		return ret
	}

	return o.LineItems
}

// GetLineItemsOk returns a tuple with the LineItems field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestFinalizeResponseData) GetLineItemsOk() ([]PaymentRequestLineItemsArray, bool) {
	if o == nil {
		return nil, false
	}
	return o.LineItems, true
}

// SetLineItems sets field value
func (o *PaymentRequestFinalizeResponseData) SetLineItems(v []PaymentRequestLineItemsArray) {
	o.LineItems = v
}

// GetTax returns the Tax field value
func (o *PaymentRequestFinalizeResponseData) GetTax() []PaymentRequestTaxArray {
	if o == nil {
		var ret []PaymentRequestTaxArray
		return ret
	}

	return o.Tax
}

// GetTaxOk returns a tuple with the Tax field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestFinalizeResponseData) GetTaxOk() ([]PaymentRequestTaxArray, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tax, true
}

// SetTax sets field value
func (o *PaymentRequestFinalizeResponseData) SetTax(v []PaymentRequestTaxArray) {
	o.Tax = v
}

// GetRequestCode returns the RequestCode field value
func (o *PaymentRequestFinalizeResponseData) GetRequestCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestCode
}

// GetRequestCodeOk returns a tuple with the RequestCode field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestFinalizeResponseData) GetRequestCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestCode, true
}

// SetRequestCode sets field value
func (o *PaymentRequestFinalizeResponseData) SetRequestCode(v string) {
	o.RequestCode = v
}

// GetStatus returns the Status field value
func (o *PaymentRequestFinalizeResponseData) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestFinalizeResponseData) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PaymentRequestFinalizeResponseData) SetStatus(v string) {
	o.Status = v
}

// GetPaid returns the Paid field value
func (o *PaymentRequestFinalizeResponseData) GetPaid() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Paid
}

// GetPaidOk returns a tuple with the Paid field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestFinalizeResponseData) GetPaidOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Paid, true
}

// SetPaid sets field value
func (o *PaymentRequestFinalizeResponseData) SetPaid(v bool) {
	o.Paid = v
}

// GetPaidAt returns the PaidAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PaymentRequestFinalizeResponseData) GetPaidAt() string {
	if o == nil || o.PaidAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.PaidAt.Get()
}

// GetPaidAtOk returns a tuple with the PaidAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentRequestFinalizeResponseData) GetPaidAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PaidAt.Get(), o.PaidAt.IsSet()
}

// SetPaidAt sets field value
func (o *PaymentRequestFinalizeResponseData) SetPaidAt(v string) {
	o.PaidAt.Set(&v)
}

// GetMetadata returns the Metadata field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *PaymentRequestFinalizeResponseData) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentRequestFinalizeResponseData) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// SetMetadata sets field value
func (o *PaymentRequestFinalizeResponseData) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetNotifications returns the Notifications field value
func (o *PaymentRequestFinalizeResponseData) GetNotifications() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Notifications
}

// GetNotificationsOk returns a tuple with the Notifications field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestFinalizeResponseData) GetNotificationsOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Notifications, true
}

// SetNotifications sets field value
func (o *PaymentRequestFinalizeResponseData) SetNotifications(v []interface{}) {
	o.Notifications = v
}

// GetOfflineReference returns the OfflineReference field value
func (o *PaymentRequestFinalizeResponseData) GetOfflineReference() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OfflineReference
}

// GetOfflineReferenceOk returns a tuple with the OfflineReference field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestFinalizeResponseData) GetOfflineReferenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OfflineReference, true
}

// SetOfflineReference sets field value
func (o *PaymentRequestFinalizeResponseData) SetOfflineReference(v string) {
	o.OfflineReference = v
}

// GetCustomer returns the Customer field value
func (o *PaymentRequestFinalizeResponseData) GetCustomer() DedicatedNubanCreateResponseDataCustomer {
	if o == nil {
		var ret DedicatedNubanCreateResponseDataCustomer
		return ret
	}

	return o.Customer
}

// GetCustomerOk returns a tuple with the Customer field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestFinalizeResponseData) GetCustomerOk() (*DedicatedNubanCreateResponseDataCustomer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Customer, true
}

// SetCustomer sets field value
func (o *PaymentRequestFinalizeResponseData) SetCustomer(v DedicatedNubanCreateResponseDataCustomer) {
	o.Customer = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PaymentRequestFinalizeResponseData) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestFinalizeResponseData) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PaymentRequestFinalizeResponseData) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetDiscount returns the Discount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentRequestFinalizeResponseData) GetDiscount() PaymentRequestFinalizeResponseDataDiscount {
	if o == nil || IsNil(o.Discount.Get()) {
		var ret PaymentRequestFinalizeResponseDataDiscount
		return ret
	}
	return *o.Discount.Get()
}

// GetDiscountOk returns a tuple with the Discount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentRequestFinalizeResponseData) GetDiscountOk() (*PaymentRequestFinalizeResponseDataDiscount, bool) {
	if o == nil {
		return nil, false
	}
	return o.Discount.Get(), o.Discount.IsSet()
}

// HasDiscount returns a boolean if a field has been set.
func (o *PaymentRequestFinalizeResponseData) HasDiscount() bool {
	if o != nil && o.Discount.IsSet() {
		return true
	}

	return false
}

// SetDiscount gets a reference to the given NullablePaymentRequestFinalizeResponseDataDiscount and assigns it to the Discount field.
func (o *PaymentRequestFinalizeResponseData) SetDiscount(v PaymentRequestFinalizeResponseDataDiscount) {
	o.Discount.Set(&v)
}
// SetDiscountNil sets the value for Discount to be an explicit nil
func (o *PaymentRequestFinalizeResponseData) SetDiscountNil() {
	o.Discount.Set(nil)
}

// UnsetDiscount ensures that no value is present for Discount, not even an explicit nil
func (o *PaymentRequestFinalizeResponseData) UnsetDiscount() {
	o.Discount.Unset()
}

// GetSplitCode returns the SplitCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentRequestFinalizeResponseData) GetSplitCode() string {
	if o == nil || IsNil(o.SplitCode.Get()) {
		var ret string
		return ret
	}
	return *o.SplitCode.Get()
}

// GetSplitCodeOk returns a tuple with the SplitCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentRequestFinalizeResponseData) GetSplitCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SplitCode.Get(), o.SplitCode.IsSet()
}

// HasSplitCode returns a boolean if a field has been set.
func (o *PaymentRequestFinalizeResponseData) HasSplitCode() bool {
	if o != nil && o.SplitCode.IsSet() {
		return true
	}

	return false
}

// SetSplitCode gets a reference to the given NullableString and assigns it to the SplitCode field.
func (o *PaymentRequestFinalizeResponseData) SetSplitCode(v string) {
	o.SplitCode.Set(&v)
}
// SetSplitCodeNil sets the value for SplitCode to be an explicit nil
func (o *PaymentRequestFinalizeResponseData) SetSplitCodeNil() {
	o.SplitCode.Set(nil)
}

// UnsetSplitCode ensures that no value is present for SplitCode, not even an explicit nil
func (o *PaymentRequestFinalizeResponseData) UnsetSplitCode() {
	o.SplitCode.Unset()
}

// GetPendingAmount returns the PendingAmount field value
func (o *PaymentRequestFinalizeResponseData) GetPendingAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PendingAmount
}

// GetPendingAmountOk returns a tuple with the PendingAmount field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestFinalizeResponseData) GetPendingAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PendingAmount, true
}

// SetPendingAmount sets field value
func (o *PaymentRequestFinalizeResponseData) SetPendingAmount(v int32) {
	o.PendingAmount = v
}

func (o PaymentRequestFinalizeResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentRequestFinalizeResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["domain"] = o.Domain
	toSerialize["amount"] = o.Amount
	toSerialize["currency"] = o.Currency
	toSerialize["due_date"] = o.DueDate.Get()
	toSerialize["has_invoice"] = o.HasInvoice
	toSerialize["invoice_number"] = o.InvoiceNumber.Get()
	toSerialize["description"] = o.Description.Get()
	toSerialize["pdf_url"] = o.PdfUrl.Get()
	toSerialize["line_items"] = o.LineItems
	toSerialize["tax"] = o.Tax
	toSerialize["request_code"] = o.RequestCode
	toSerialize["status"] = o.Status
	toSerialize["paid"] = o.Paid
	toSerialize["paid_at"] = o.PaidAt.Get()
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["notifications"] = o.Notifications
	toSerialize["offline_reference"] = o.OfflineReference
	toSerialize["customer"] = o.Customer
	toSerialize["created_at"] = o.CreatedAt
	if o.Discount.IsSet() {
		toSerialize["discount"] = o.Discount.Get()
	}
	if o.SplitCode.IsSet() {
		toSerialize["split_code"] = o.SplitCode.Get()
	}
	toSerialize["pending_amount"] = o.PendingAmount
	return toSerialize, nil
}

func (o *PaymentRequestFinalizeResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"domain",
		"amount",
		"currency",
		"due_date",
		"has_invoice",
		"invoice_number",
		"description",
		"pdf_url",
		"line_items",
		"tax",
		"request_code",
		"status",
		"paid",
		"paid_at",
		"metadata",
		"notifications",
		"offline_reference",
		"customer",
		"created_at",
		"pending_amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentRequestFinalizeResponseData := _PaymentRequestFinalizeResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaymentRequestFinalizeResponseData)

	if err != nil {
		return err
	}

	*o = PaymentRequestFinalizeResponseData(varPaymentRequestFinalizeResponseData)

	return err
}

type NullablePaymentRequestFinalizeResponseData struct {
	value *PaymentRequestFinalizeResponseData
	isSet bool
}

func (v NullablePaymentRequestFinalizeResponseData) Get() *PaymentRequestFinalizeResponseData {
	return v.value
}

func (v *NullablePaymentRequestFinalizeResponseData) Set(val *PaymentRequestFinalizeResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentRequestFinalizeResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentRequestFinalizeResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentRequestFinalizeResponseData(val *PaymentRequestFinalizeResponseData) *NullablePaymentRequestFinalizeResponseData {
	return &NullablePaymentRequestFinalizeResponseData{value: val, isSet: true}
}

func (v NullablePaymentRequestFinalizeResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentRequestFinalizeResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


