/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.4.1
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookEventOneOf20 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookEventOneOf20{}

// WebhookEventOneOf20 struct for WebhookEventOneOf20
type WebhookEventOneOf20 struct {
	Event string `json:"event"`
	Data Data7 `json:"data"`
}

type _WebhookEventOneOf20 WebhookEventOneOf20

// NewWebhookEventOneOf20 instantiates a new WebhookEventOneOf20 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookEventOneOf20(event string, data Data7) *WebhookEventOneOf20 {
	this := WebhookEventOneOf20{}
	this.Event = event
	this.Data = data
	return &this
}

// NewWebhookEventOneOf20WithDefaults instantiates a new WebhookEventOneOf20 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookEventOneOf20WithDefaults() *WebhookEventOneOf20 {
	this := WebhookEventOneOf20{}
	return &this
}

// GetEvent returns the Event field value
func (o *WebhookEventOneOf20) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *WebhookEventOneOf20) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *WebhookEventOneOf20) SetEvent(v string) {
	o.Event = v
}

// GetData returns the Data field value
func (o *WebhookEventOneOf20) GetData() Data7 {
	if o == nil {
		var ret Data7
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *WebhookEventOneOf20) GetDataOk() (*Data7, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *WebhookEventOneOf20) SetData(v Data7) {
	o.Data = v
}

func (o WebhookEventOneOf20) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookEventOneOf20) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *WebhookEventOneOf20) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookEventOneOf20 := _WebhookEventOneOf20{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookEventOneOf20)

	if err != nil {
		return err
	}

	*o = WebhookEventOneOf20(varWebhookEventOneOf20)

	return err
}

type NullableWebhookEventOneOf20 struct {
	value *WebhookEventOneOf20
	isSet bool
}

func (v NullableWebhookEventOneOf20) Get() *WebhookEventOneOf20 {
	return v.value
}

func (v *NullableWebhookEventOneOf20) Set(val *WebhookEventOneOf20) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookEventOneOf20) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookEventOneOf20) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookEventOneOf20(val *WebhookEventOneOf20) *NullableWebhookEventOneOf20 {
	return &NullableWebhookEventOneOf20{value: val, isSet: true}
}

func (v NullableWebhookEventOneOf20) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookEventOneOf20) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


