/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
)

// checks if the VerificationResolveCardBINResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerificationResolveCardBINResponseData{}

// VerificationResolveCardBINResponseData struct for VerificationResolveCardBINResponseData
type VerificationResolveCardBINResponseData struct {
	Bin string `json:"bin"`
	Brand string `json:"brand"`
	SubBrand string `json:"sub_brand"`
	CountryCode string `json:"country_code"`
	CountryName string `json:"country_name"`
	CardType string `json:"card_type"`
	Bank string `json:"bank"`
	Currency string `json:"currency"`
	LinkedBankId int32 `json:"linked_bank_id"`
}

// NewVerificationResolveCardBINResponseData instantiates a new VerificationResolveCardBINResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerificationResolveCardBINResponseData(bin string, brand string, subBrand string, countryCode string, countryName string, cardType string, bank string, currency string, linkedBankId int32) *VerificationResolveCardBINResponseData {
	this := VerificationResolveCardBINResponseData{}
	this.Bin = bin
	this.Brand = brand
	this.SubBrand = subBrand
	this.CountryCode = countryCode
	this.CountryName = countryName
	this.CardType = cardType
	this.Bank = bank
	this.Currency = currency
	this.LinkedBankId = linkedBankId
	return &this
}

// NewVerificationResolveCardBINResponseDataWithDefaults instantiates a new VerificationResolveCardBINResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerificationResolveCardBINResponseDataWithDefaults() *VerificationResolveCardBINResponseData {
	this := VerificationResolveCardBINResponseData{}
	return &this
}

// GetBin returns the Bin field value
func (o *VerificationResolveCardBINResponseData) GetBin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bin
}

// GetBinOk returns a tuple with the Bin field value
// and a boolean to check if the value has been set.
func (o *VerificationResolveCardBINResponseData) GetBinOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bin, true
}

// SetBin sets field value
func (o *VerificationResolveCardBINResponseData) SetBin(v string) {
	o.Bin = v
}

// GetBrand returns the Brand field value
func (o *VerificationResolveCardBINResponseData) GetBrand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Brand
}

// GetBrandOk returns a tuple with the Brand field value
// and a boolean to check if the value has been set.
func (o *VerificationResolveCardBINResponseData) GetBrandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Brand, true
}

// SetBrand sets field value
func (o *VerificationResolveCardBINResponseData) SetBrand(v string) {
	o.Brand = v
}

// GetSubBrand returns the SubBrand field value
func (o *VerificationResolveCardBINResponseData) GetSubBrand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubBrand
}

// GetSubBrandOk returns a tuple with the SubBrand field value
// and a boolean to check if the value has been set.
func (o *VerificationResolveCardBINResponseData) GetSubBrandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubBrand, true
}

// SetSubBrand sets field value
func (o *VerificationResolveCardBINResponseData) SetSubBrand(v string) {
	o.SubBrand = v
}

// GetCountryCode returns the CountryCode field value
func (o *VerificationResolveCardBINResponseData) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *VerificationResolveCardBINResponseData) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *VerificationResolveCardBINResponseData) SetCountryCode(v string) {
	o.CountryCode = v
}

// GetCountryName returns the CountryName field value
func (o *VerificationResolveCardBINResponseData) GetCountryName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryName
}

// GetCountryNameOk returns a tuple with the CountryName field value
// and a boolean to check if the value has been set.
func (o *VerificationResolveCardBINResponseData) GetCountryNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryName, true
}

// SetCountryName sets field value
func (o *VerificationResolveCardBINResponseData) SetCountryName(v string) {
	o.CountryName = v
}

// GetCardType returns the CardType field value
func (o *VerificationResolveCardBINResponseData) GetCardType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CardType
}

// GetCardTypeOk returns a tuple with the CardType field value
// and a boolean to check if the value has been set.
func (o *VerificationResolveCardBINResponseData) GetCardTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CardType, true
}

// SetCardType sets field value
func (o *VerificationResolveCardBINResponseData) SetCardType(v string) {
	o.CardType = v
}

// GetBank returns the Bank field value
func (o *VerificationResolveCardBINResponseData) GetBank() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bank
}

// GetBankOk returns a tuple with the Bank field value
// and a boolean to check if the value has been set.
func (o *VerificationResolveCardBINResponseData) GetBankOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bank, true
}

// SetBank sets field value
func (o *VerificationResolveCardBINResponseData) SetBank(v string) {
	o.Bank = v
}

// GetCurrency returns the Currency field value
func (o *VerificationResolveCardBINResponseData) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *VerificationResolveCardBINResponseData) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *VerificationResolveCardBINResponseData) SetCurrency(v string) {
	o.Currency = v
}

// GetLinkedBankId returns the LinkedBankId field value
func (o *VerificationResolveCardBINResponseData) GetLinkedBankId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LinkedBankId
}

// GetLinkedBankIdOk returns a tuple with the LinkedBankId field value
// and a boolean to check if the value has been set.
func (o *VerificationResolveCardBINResponseData) GetLinkedBankIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LinkedBankId, true
}

// SetLinkedBankId sets field value
func (o *VerificationResolveCardBINResponseData) SetLinkedBankId(v int32) {
	o.LinkedBankId = v
}

func (o VerificationResolveCardBINResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerificationResolveCardBINResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bin"] = o.Bin
	toSerialize["brand"] = o.Brand
	toSerialize["sub_brand"] = o.SubBrand
	toSerialize["country_code"] = o.CountryCode
	toSerialize["country_name"] = o.CountryName
	toSerialize["card_type"] = o.CardType
	toSerialize["bank"] = o.Bank
	toSerialize["currency"] = o.Currency
	toSerialize["linked_bank_id"] = o.LinkedBankId
	return toSerialize, nil
}

type NullableVerificationResolveCardBINResponseData struct {
	value *VerificationResolveCardBINResponseData
	isSet bool
}

func (v NullableVerificationResolveCardBINResponseData) Get() *VerificationResolveCardBINResponseData {
	return v.value
}

func (v *NullableVerificationResolveCardBINResponseData) Set(val *VerificationResolveCardBINResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableVerificationResolveCardBINResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableVerificationResolveCardBINResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerificationResolveCardBINResponseData(val *VerificationResolveCardBINResponseData) *NullableVerificationResolveCardBINResponseData {
	return &NullableVerificationResolveCardBINResponseData{value: val, isSet: true}
}

func (v NullableVerificationResolveCardBINResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerificationResolveCardBINResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


