/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
)

// checks if the CustomerFetchMandateAuthorizationsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerFetchMandateAuthorizationsResponse{}

// CustomerFetchMandateAuthorizationsResponse struct for CustomerFetchMandateAuthorizationsResponse
type CustomerFetchMandateAuthorizationsResponse struct {
	Status bool `json:"status"`
	Message string `json:"message"`
	Data []CustomerFetchMandateAuthorizationsResponseData `json:"data"`
	Meta CustomerFetchMandateAuthorizationsResponseMeta `json:"meta"`
}

// NewCustomerFetchMandateAuthorizationsResponse instantiates a new CustomerFetchMandateAuthorizationsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerFetchMandateAuthorizationsResponse(status bool, message string, data []CustomerFetchMandateAuthorizationsResponseData, meta CustomerFetchMandateAuthorizationsResponseMeta) *CustomerFetchMandateAuthorizationsResponse {
	this := CustomerFetchMandateAuthorizationsResponse{}
	this.Status = status
	this.Message = message
	this.Data = data
	this.Meta = meta
	return &this
}

// NewCustomerFetchMandateAuthorizationsResponseWithDefaults instantiates a new CustomerFetchMandateAuthorizationsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerFetchMandateAuthorizationsResponseWithDefaults() *CustomerFetchMandateAuthorizationsResponse {
	this := CustomerFetchMandateAuthorizationsResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *CustomerFetchMandateAuthorizationsResponse) GetStatus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CustomerFetchMandateAuthorizationsResponse) GetStatusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CustomerFetchMandateAuthorizationsResponse) SetStatus(v bool) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *CustomerFetchMandateAuthorizationsResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *CustomerFetchMandateAuthorizationsResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *CustomerFetchMandateAuthorizationsResponse) SetMessage(v string) {
	o.Message = v
}

// GetData returns the Data field value
func (o *CustomerFetchMandateAuthorizationsResponse) GetData() []CustomerFetchMandateAuthorizationsResponseData {
	if o == nil {
		var ret []CustomerFetchMandateAuthorizationsResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CustomerFetchMandateAuthorizationsResponse) GetDataOk() ([]CustomerFetchMandateAuthorizationsResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CustomerFetchMandateAuthorizationsResponse) SetData(v []CustomerFetchMandateAuthorizationsResponseData) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *CustomerFetchMandateAuthorizationsResponse) GetMeta() CustomerFetchMandateAuthorizationsResponseMeta {
	if o == nil {
		var ret CustomerFetchMandateAuthorizationsResponseMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *CustomerFetchMandateAuthorizationsResponse) GetMetaOk() (*CustomerFetchMandateAuthorizationsResponseMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *CustomerFetchMandateAuthorizationsResponse) SetMeta(v CustomerFetchMandateAuthorizationsResponseMeta) {
	o.Meta = v
}

func (o CustomerFetchMandateAuthorizationsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerFetchMandateAuthorizationsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	toSerialize["data"] = o.Data
	toSerialize["meta"] = o.Meta
	return toSerialize, nil
}

type NullableCustomerFetchMandateAuthorizationsResponse struct {
	value *CustomerFetchMandateAuthorizationsResponse
	isSet bool
}

func (v NullableCustomerFetchMandateAuthorizationsResponse) Get() *CustomerFetchMandateAuthorizationsResponse {
	return v.value
}

func (v *NullableCustomerFetchMandateAuthorizationsResponse) Set(val *CustomerFetchMandateAuthorizationsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerFetchMandateAuthorizationsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerFetchMandateAuthorizationsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerFetchMandateAuthorizationsResponse(val *CustomerFetchMandateAuthorizationsResponse) *NullableCustomerFetchMandateAuthorizationsResponse {
	return &NullableCustomerFetchMandateAuthorizationsResponse{value: val, isSet: true}
}

func (v NullableCustomerFetchMandateAuthorizationsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerFetchMandateAuthorizationsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


