/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
)

// checks if the DedicatedNubanListResponseArraySplitConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DedicatedNubanListResponseArraySplitConfig{}

// DedicatedNubanListResponseArraySplitConfig struct for DedicatedNubanListResponseArraySplitConfig
type DedicatedNubanListResponseArraySplitConfig struct {
	Subaccount string `json:"subaccount"`
}

// NewDedicatedNubanListResponseArraySplitConfig instantiates a new DedicatedNubanListResponseArraySplitConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDedicatedNubanListResponseArraySplitConfig(subaccount string) *DedicatedNubanListResponseArraySplitConfig {
	this := DedicatedNubanListResponseArraySplitConfig{}
	this.Subaccount = subaccount
	return &this
}

// NewDedicatedNubanListResponseArraySplitConfigWithDefaults instantiates a new DedicatedNubanListResponseArraySplitConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDedicatedNubanListResponseArraySplitConfigWithDefaults() *DedicatedNubanListResponseArraySplitConfig {
	this := DedicatedNubanListResponseArraySplitConfig{}
	return &this
}

// GetSubaccount returns the Subaccount field value
func (o *DedicatedNubanListResponseArraySplitConfig) GetSubaccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subaccount
}

// GetSubaccountOk returns a tuple with the Subaccount field value
// and a boolean to check if the value has been set.
func (o *DedicatedNubanListResponseArraySplitConfig) GetSubaccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subaccount, true
}

// SetSubaccount sets field value
func (o *DedicatedNubanListResponseArraySplitConfig) SetSubaccount(v string) {
	o.Subaccount = v
}

func (o DedicatedNubanListResponseArraySplitConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DedicatedNubanListResponseArraySplitConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subaccount"] = o.Subaccount
	return toSerialize, nil
}

type NullableDedicatedNubanListResponseArraySplitConfig struct {
	value *DedicatedNubanListResponseArraySplitConfig
	isSet bool
}

func (v NullableDedicatedNubanListResponseArraySplitConfig) Get() *DedicatedNubanListResponseArraySplitConfig {
	return v.value
}

func (v *NullableDedicatedNubanListResponseArraySplitConfig) Set(val *DedicatedNubanListResponseArraySplitConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableDedicatedNubanListResponseArraySplitConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableDedicatedNubanListResponseArraySplitConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDedicatedNubanListResponseArraySplitConfig(val *DedicatedNubanListResponseArraySplitConfig) *NullableDedicatedNubanListResponseArraySplitConfig {
	return &NullableDedicatedNubanListResponseArraySplitConfig{value: val, isSet: true}
}

func (v NullableDedicatedNubanListResponseArraySplitConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDedicatedNubanListResponseArraySplitConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


