/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TerminalDecommissionDeviceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TerminalDecommissionDeviceResponse{}

// TerminalDecommissionDeviceResponse struct for TerminalDecommissionDeviceResponse
type TerminalDecommissionDeviceResponse struct {
	Status bool `json:"status"`
	Message string `json:"message"`
}

type _TerminalDecommissionDeviceResponse TerminalDecommissionDeviceResponse

// NewTerminalDecommissionDeviceResponse instantiates a new TerminalDecommissionDeviceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTerminalDecommissionDeviceResponse(status bool, message string) *TerminalDecommissionDeviceResponse {
	this := TerminalDecommissionDeviceResponse{}
	this.Status = status
	this.Message = message
	return &this
}

// NewTerminalDecommissionDeviceResponseWithDefaults instantiates a new TerminalDecommissionDeviceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTerminalDecommissionDeviceResponseWithDefaults() *TerminalDecommissionDeviceResponse {
	this := TerminalDecommissionDeviceResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *TerminalDecommissionDeviceResponse) GetStatus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TerminalDecommissionDeviceResponse) GetStatusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TerminalDecommissionDeviceResponse) SetStatus(v bool) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *TerminalDecommissionDeviceResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *TerminalDecommissionDeviceResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *TerminalDecommissionDeviceResponse) SetMessage(v string) {
	o.Message = v
}

func (o TerminalDecommissionDeviceResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TerminalDecommissionDeviceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *TerminalDecommissionDeviceResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTerminalDecommissionDeviceResponse := _TerminalDecommissionDeviceResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTerminalDecommissionDeviceResponse)

	if err != nil {
		return err
	}

	*o = TerminalDecommissionDeviceResponse(varTerminalDecommissionDeviceResponse)

	return err
}

type NullableTerminalDecommissionDeviceResponse struct {
	value *TerminalDecommissionDeviceResponse
	isSet bool
}

func (v NullableTerminalDecommissionDeviceResponse) Get() *TerminalDecommissionDeviceResponse {
	return v.value
}

func (v *NullableTerminalDecommissionDeviceResponse) Set(val *TerminalDecommissionDeviceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTerminalDecommissionDeviceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTerminalDecommissionDeviceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerminalDecommissionDeviceResponse(val *TerminalDecommissionDeviceResponse) *NullableTerminalDecommissionDeviceResponse {
	return &NullableTerminalDecommissionDeviceResponse{value: val, isSet: true}
}

func (v NullableTerminalDecommissionDeviceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerminalDecommissionDeviceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


