/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaymentRequestArchiveResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentRequestArchiveResponse{}

// PaymentRequestArchiveResponse struct for PaymentRequestArchiveResponse
type PaymentRequestArchiveResponse struct {
	Status bool `json:"status"`
	Message string `json:"message"`
}

type _PaymentRequestArchiveResponse PaymentRequestArchiveResponse

// NewPaymentRequestArchiveResponse instantiates a new PaymentRequestArchiveResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentRequestArchiveResponse(status bool, message string) *PaymentRequestArchiveResponse {
	this := PaymentRequestArchiveResponse{}
	this.Status = status
	this.Message = message
	return &this
}

// NewPaymentRequestArchiveResponseWithDefaults instantiates a new PaymentRequestArchiveResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentRequestArchiveResponseWithDefaults() *PaymentRequestArchiveResponse {
	this := PaymentRequestArchiveResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *PaymentRequestArchiveResponse) GetStatus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestArchiveResponse) GetStatusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PaymentRequestArchiveResponse) SetStatus(v bool) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *PaymentRequestArchiveResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestArchiveResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *PaymentRequestArchiveResponse) SetMessage(v string) {
	o.Message = v
}

func (o PaymentRequestArchiveResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentRequestArchiveResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *PaymentRequestArchiveResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentRequestArchiveResponse := _PaymentRequestArchiveResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaymentRequestArchiveResponse)

	if err != nil {
		return err
	}

	*o = PaymentRequestArchiveResponse(varPaymentRequestArchiveResponse)

	return err
}

type NullablePaymentRequestArchiveResponse struct {
	value *PaymentRequestArchiveResponse
	isSet bool
}

func (v NullablePaymentRequestArchiveResponse) Get() *PaymentRequestArchiveResponse {
	return v.value
}

func (v *NullablePaymentRequestArchiveResponse) Set(val *PaymentRequestArchiveResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentRequestArchiveResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentRequestArchiveResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentRequestArchiveResponse(val *PaymentRequestArchiveResponse) *NullablePaymentRequestArchiveResponse {
	return &NullablePaymentRequestArchiveResponse{value: val, isSet: true}
}

func (v NullablePaymentRequestArchiveResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentRequestArchiveResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


