/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.0.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
)

// checks if the PaymentRequestTotalArray type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentRequestTotalArray{}

// PaymentRequestTotalArray struct for PaymentRequestTotalArray
type PaymentRequestTotalArray struct {
	Currency string `json:"currency"`
	Amount int32 `json:"amount"`
}

// NewPaymentRequestTotalArray instantiates a new PaymentRequestTotalArray object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentRequestTotalArray(currency string, amount int32) *PaymentRequestTotalArray {
	this := PaymentRequestTotalArray{}
	this.Currency = currency
	this.Amount = amount
	return &this
}

// NewPaymentRequestTotalArrayWithDefaults instantiates a new PaymentRequestTotalArray object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentRequestTotalArrayWithDefaults() *PaymentRequestTotalArray {
	this := PaymentRequestTotalArray{}
	return &this
}

// GetCurrency returns the Currency field value
func (o *PaymentRequestTotalArray) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestTotalArray) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *PaymentRequestTotalArray) SetCurrency(v string) {
	o.Currency = v
}

// GetAmount returns the Amount field value
func (o *PaymentRequestTotalArray) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *PaymentRequestTotalArray) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *PaymentRequestTotalArray) SetAmount(v int32) {
	o.Amount = v
}

func (o PaymentRequestTotalArray) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentRequestTotalArray) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["currency"] = o.Currency
	toSerialize["amount"] = o.Amount
	return toSerialize, nil
}

type NullablePaymentRequestTotalArray struct {
	value *PaymentRequestTotalArray
	isSet bool
}

func (v NullablePaymentRequestTotalArray) Get() *PaymentRequestTotalArray {
	return v.value
}

func (v *NullablePaymentRequestTotalArray) Set(val *PaymentRequestTotalArray) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentRequestTotalArray) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentRequestTotalArray) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentRequestTotalArray(val *PaymentRequestTotalArray) *NullablePaymentRequestTotalArray {
	return &NullablePaymentRequestTotalArray{value: val, isSet: true}
}

func (v NullablePaymentRequestTotalArray) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentRequestTotalArray) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


