/*
Paystack

The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

API version: 1.4.0
Contact: techsupport@paystack.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paystack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookEventOneOf10 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookEventOneOf10{}

// WebhookEventOneOf10 struct for WebhookEventOneOf10
type WebhookEventOneOf10 struct {
	Event string `json:"event"`
	Data Data5 `json:"data"`
}

type _WebhookEventOneOf10 WebhookEventOneOf10

// NewWebhookEventOneOf10 instantiates a new WebhookEventOneOf10 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookEventOneOf10(event string, data Data5) *WebhookEventOneOf10 {
	this := WebhookEventOneOf10{}
	this.Event = event
	this.Data = data
	return &this
}

// NewWebhookEventOneOf10WithDefaults instantiates a new WebhookEventOneOf10 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookEventOneOf10WithDefaults() *WebhookEventOneOf10 {
	this := WebhookEventOneOf10{}
	return &this
}

// GetEvent returns the Event field value
func (o *WebhookEventOneOf10) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *WebhookEventOneOf10) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *WebhookEventOneOf10) SetEvent(v string) {
	o.Event = v
}

// GetData returns the Data field value
func (o *WebhookEventOneOf10) GetData() Data5 {
	if o == nil {
		var ret Data5
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *WebhookEventOneOf10) GetDataOk() (*Data5, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *WebhookEventOneOf10) SetData(v Data5) {
	o.Data = v
}

func (o WebhookEventOneOf10) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookEventOneOf10) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *WebhookEventOneOf10) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookEventOneOf10 := _WebhookEventOneOf10{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookEventOneOf10)

	if err != nil {
		return err
	}

	*o = WebhookEventOneOf10(varWebhookEventOneOf10)

	return err
}

type NullableWebhookEventOneOf10 struct {
	value *WebhookEventOneOf10
	isSet bool
}

func (v NullableWebhookEventOneOf10) Get() *WebhookEventOneOf10 {
	return v.value
}

func (v *NullableWebhookEventOneOf10) Set(val *WebhookEventOneOf10) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookEventOneOf10) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookEventOneOf10) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookEventOneOf10(val *WebhookEventOneOf10) *NullableWebhookEventOneOf10 {
	return &NullableWebhookEventOneOf10{value: val, isSet: true}
}

func (v NullableWebhookEventOneOf10) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookEventOneOf10) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


