name: Run Spectral on Pull Requests

on:
  - pull_request

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint SDK specification
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: "sdk/*.yaml"
      - name: Lint distribution specification
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: "dist/*.yaml"
